<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introduction to R and RStudio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="https://www2.hshsl.umaryland.edu/cdabs/" class="navbar-brand navbar-brand-logo">
    <img src="https://www2.hshsl.umaryland.edu/hshsl/bin/img/logo_white@2x.png" alt="HSHSL logo" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./01-RBasics.html" aria-current="page"> 
<span class="menu-text">R Basics</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./02-DataWrangling.html"> 
<span class="menu-text">Data Wrangling</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./03-DataVisualization.html"> 
<span class="menu-text">Data Visualization</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#why-learn-r" id="toc-why-learn-r" class="nav-link" data-scroll-target="#why-learn-r">Why learn R?</a></li>
  <li><a href="#starting-out-in-r" id="toc-starting-out-in-r" class="nav-link" data-scroll-target="#starting-out-in-r">Starting out in R</a>
  <ul class="collapse">
  <li><a href="#downloading-installing-and-running-r" id="toc-downloading-installing-and-running-r" class="nav-link" data-scroll-target="#downloading-installing-and-running-r">Downloading, Installing and Running R</a></li>
  <li><a href="#rstudio" id="toc-rstudio" class="nav-link" data-scroll-target="#rstudio">RStudio</a></li>
  </ul></li>
  <li><a href="#working-in-the-console" id="toc-working-in-the-console" class="nav-link" data-scroll-target="#working-in-the-console">Working in the Console</a></li>
  <li><a href="#objects" id="toc-objects" class="nav-link" data-scroll-target="#objects">Objects</a>
  <ul class="collapse">
  <li><a href="#creating-objects" id="toc-creating-objects" class="nav-link" data-scroll-target="#creating-objects">Creating Objects</a></li>
  <li><a href="#try-it-yourself" id="toc-try-it-yourself" class="nav-link" data-scroll-target="#try-it-yourself">Try it Yourself!</a></li>
  <li><a href="#working-with-objects" id="toc-working-with-objects" class="nav-link" data-scroll-target="#working-with-objects">Working with Objects</a></li>
  <li><a href="#try-it-yourself-1" id="toc-try-it-yourself-1" class="nav-link" data-scroll-target="#try-it-yourself-1">Try it Yourself!</a></li>
  </ul></li>
  <li><a href="#saving-code-in-an-r-script" id="toc-saving-code-in-an-r-script" class="nav-link" data-scroll-target="#saving-code-in-an-r-script">Saving code in an R script</a></li>
  <li><a href="#setting-your-working-directory" id="toc-setting-your-working-directory" class="nav-link" data-scroll-target="#setting-your-working-directory">Setting your Working Directory</a></li>
  <li><a href="#functions-and-their-arguments" id="toc-functions-and-their-arguments" class="nav-link" data-scroll-target="#functions-and-their-arguments">Functions and their arguments</a>
  <ul class="collapse">
  <li><a href="#getting-help" id="toc-getting-help" class="nav-link" data-scroll-target="#getting-help">Getting Help</a></li>
  <li><a href="#try-it-yourself-2" id="toc-try-it-yourself-2" class="nav-link" data-scroll-target="#try-it-yourself-2">Try it Yourself!</a></li>
  </ul></li>
  <li><a href="#vectors" id="toc-vectors" class="nav-link" data-scroll-target="#vectors">Vectors</a>
  <ul class="collapse">
  <li><a href="#what-is-a-vector" id="toc-what-is-a-vector" class="nav-link" data-scroll-target="#what-is-a-vector">What is a Vector?</a></li>
  <li><a href="#working-with-vectors" id="toc-working-with-vectors" class="nav-link" data-scroll-target="#working-with-vectors">Working with Vectors</a></li>
  <li><a href="#try-it-yourself-3" id="toc-try-it-yourself-3" class="nav-link" data-scroll-target="#try-it-yourself-3">Try it Yourself!</a></li>
  <li><a href="#missing-data" id="toc-missing-data" class="nav-link" data-scroll-target="#missing-data">Missing Data</a></li>
  <li><a href="#mixing-data-types" id="toc-mixing-data-types" class="nav-link" data-scroll-target="#mixing-data-types">Mixing Data Types</a></li>
  <li><a href="#try-it-yourself-4" id="toc-try-it-yourself-4" class="nav-link" data-scroll-target="#try-it-yourself-4">Try it Yourself!</a></li>
  <li><a href="#indexing-and-subsetting-vectors" id="toc-indexing-and-subsetting-vectors" class="nav-link" data-scroll-target="#indexing-and-subsetting-vectors">Indexing and Subsetting vectors</a></li>
  <li><a href="#try-it-yourself-5" id="toc-try-it-yourself-5" class="nav-link" data-scroll-target="#try-it-yourself-5">Try it Yourself!</a></li>
  </ul></li>
  <li><a href="#data-frames-tibbles-and-exploring-data" id="toc-data-frames-tibbles-and-exploring-data" class="nav-link" data-scroll-target="#data-frames-tibbles-and-exploring-data">Data frames, Tibbles, and Exploring Data</a>
  <ul class="collapse">
  <li><a href="#creating-data-frames" id="toc-creating-data-frames" class="nav-link" data-scroll-target="#creating-data-frames">Creating data frames</a></li>
  <li><a href="#exploring-data-frames" id="toc-exploring-data-frames" class="nav-link" data-scroll-target="#exploring-data-frames">Exploring data frames</a></li>
  <li><a href="#try-it-yourself-6" id="toc-try-it-yourself-6" class="nav-link" data-scroll-target="#try-it-yourself-6">Try it Yourself!</a></li>
  <li><a href="#quickly-exploring-data-with-plots" id="toc-quickly-exploring-data-with-plots" class="nav-link" data-scroll-target="#quickly-exploring-data-with-plots">Quickly exploring data with plots</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://hshsl-training.github.io/intro-to-r/edit/main/01-RBasics.Rmd" class="toc-action"><i class="bi bi-git"></i>Edit this page</a></li><li><a href="https://hshsl-training.github.io/intro-to-r/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Introduction to R and RStudio</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<ul>
<li>Understand the value of learning R</li>
<li>Navigate RStudio</li>
<li>Define terms: object, function, argument, package, vector, data frame.</li>
<li>Use help documentation in RStudio.</li>
</ul>
</section>
<section id="why-learn-r" class="level2">
<h2 class="anchored" data-anchor-id="why-learn-r">Why learn R?</h2>
<ul>
<li><p><strong>R is free, open-source, and cross-platform.</strong> Anyone can inspect the source code to see how R works. Because of this transparency, there is less chance for mistakes, and if you (or someone else) find some, you can report and fix bugs. Because R is open source and is supported by a large community of developers and users, there is a very large selection of third-party add-on packages which are freely available to extend R’s native capabilities.</p></li>
<li><p><strong>R code is great for reproducibility</strong>. Reproducibility is when someone else (including your future self) can obtain the same results from the same dataset when using the same analysis. R integrates with other tools to generate manuscripts from your code. If you collect more data, or fix a mistake in your dataset, the figures and the statistical tests in your manuscript are updated automatically.</p></li>
<li><p><strong>R relies on a series of written commands, not on remembering a succession of pointing and clicking.</strong> If you want to redo your analysis because you collected more data, you don’t have to remember which button you clicked in which order to obtain your results; you just have to run your script again.</p></li>
<li><p><strong>R is interdisciplinary and extensible</strong> With 10,000+ packages that can be installed to extend its capabilities, R provides a framework that allows you to combine statistical approaches from many scientific disciplines to best suit the analytical framework you need to analyze your data. For instance, R has packages for image analysis, GIS, time series, population genetics, and a lot more.</p></li>
<li><p><strong>R works on data of all shapes and sizes.</strong> The skills you learn with R scale easily with the size of your dataset. Whether your dataset has hundreds or millions of lines, it won’t make much difference to you. R is designed for data analysis. It comes with special data structures and data types that make handling of missing data and statistical factors convenient. R can connect to spreadsheets, databases, and many other data formats, on your computer or on the web.</p></li>
<li><p><strong>R produces high-quality graphics.</strong> The plotting functionalities in R are endless, and allow you to adjust any aspect of your graph to convey most effectively the message from your data.</p></li>
<li><p><strong>R has a large and welcoming community.</strong> Thousands of people use R daily. Many of them are willing to help you through mailing lists and websites such as <a href="https://stackoverflow.com/">Stack Overflow</a>, or on the <a href="https://community.rstudio.com/">RStudio community</a>. Questions which are backed up with <a href="https://www.tidyverse.org/help/">short, reproducible code snippets</a> are more likely to attract knowledgeable responses.</p></li>
</ul>
</section>
<section id="starting-out-in-r" class="level2">
<h2 class="anchored" data-anchor-id="starting-out-in-r">Starting out in R</h2>
<p><a href="https://cran.rstudio.com/">R</a> is both a programming language and an interactive environment for data exploration and statistics.</p>
<p>Working with R is primarily text-based. The basic mode of use for R is that the user provides commands in the R language and then R computes and displays the result.</p>
<section id="downloading-installing-and-running-r" class="level3">
<h3 class="anchored" data-anchor-id="downloading-installing-and-running-r">Downloading, Installing and Running R</h3>
<p><strong>Download</strong><br>
R can be downloaded from <a href="https://cran.rstudio.com/index.html">CRAN (The Comprehensive R Archive Network)</a> for Windows, Linux, or Mac.</p>
<p><strong>Install</strong><br>
Installation of R is like most software packages and you will be guided. Should you have any issues or need help you can refer to <a href="https://cran.r-project.org/doc/manuals/r-release/R-admin.html">R Installation and Administration</a></p>
<p><strong>Running</strong><br>
R can be launched from your software or applications launcher or When working at a command line on UNIX or Windows, the command <code>R</code> can be used for starting the main R program in the form <code>R</code></p>
<p>You will see a console similar to this appear:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/console.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="414"></p>
</figure>
</div>
</div>
</div>
<p>While it is possible to work solely through the console or using a command line interface, the ideal environment to work in R is RStudio.</p>
</section>
<section id="rstudio" class="level3">
<h3 class="anchored" data-anchor-id="rstudio">RStudio</h3>
<p><a href="https://www.rstudio.com/products/rstudio/download/">RStudio</a> is a user interface for working with R. It is called an Integrated Development Environment (IDE): a piece of software that provides tools to make programming easier. RStudio acts as a sort of wrapper around the R language. You can use R without RStudio, but it’s much more limiting. RStudio makes it easier to import datasets, create and write scripts, and makes using R much more effective. RStudio is also free and open source. To function correctly, RStudio needs R and therefore both need to be installed on your computer. But for this class we’ll be using a browser based version called RStudio Cloud (see directions in the [RStudio Cloud] section below.)</p>
<p>RStudio is divided into four “panes”. The placement of these panes and their content can be customized (see menu, Tools -&gt; Global Options -&gt; Pane Layout).</p>
<p>The Default Layout is:</p>
<ul>
<li>Top Left - <strong>Source</strong>: your scripts and documents</li>
<li>Bottom Left - <strong>Console</strong>: what R would look and be like without RStudio</li>
<li>Top Right - <strong>Environment/History</strong>: look here to see what you have done</li>
<li>Bottom Right - <strong>Files</strong> and more: see the contents of the project/working directory here, like your Script.R file</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/rstudio.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1002"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" data-appearence="minimal">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Follow Along at Home
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>There are two options:</p>
<section id="rstudio-1" class="level4">
<h4 class="anchored" data-anchor-id="rstudio-1">RStudio</h4>
<ol type="1">
<li>Follow the instructions above to download R and RStudio to your personal computer</li>
<li>Download the folder <code>Session01_RBasics</code> from <a href="https://osf.io/6ra5v/files/osfstorage" class="uri">https://osf.io/6ra5v/files/osfstorage</a> and unzip it to your computer in a place you’ll be able to find it easily, such as your Desktop or Documents folder.</li>
</ol>
</section>
<section id="posit-cloud" class="level4">
<h4 class="anchored" data-anchor-id="posit-cloud">Posit Cloud</h4>
<p>Posit (RStudio) Cloud is a browser-based version of RStudio. It will allow you to use RStudio without needing to download anything to your computer. Posit Cloud automatically organizes things into Projects. You can also easily share your R projects with others.</p>
<p>Get Started:</p>
<ol type="1">
<li>Create your free RStudio Cloud account at <a href="https://rstudio.cloud/plans/free" class="uri">https://rstudio.cloud/plans/free</a>.</li>
<li>Go to the class project <a href="https://rstudio.cloud/content/4241048" class="uri">https://rstudio.cloud/content/4241048</a></li>
<li>Note the text that marks this as a Temporary Copy. Select the <code>Save a Permanent Copy</code> button to begin working!</li>
</ol>
</section>
</div>
</div>
</div>
</section>
</section>
<section id="working-in-the-console" class="level2">
<h2 class="anchored" data-anchor-id="working-in-the-console">Working in the Console</h2>
<p>The console is an interactive environment for RStudio, click on the “Console” pane, type <code>3 + 3</code> and press enter. R displays the result of the calculation.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r source code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="dv">3</span> <span class="sc">+</span> <span class="dv">3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>[1] 6</code></pre>
</div>
</div>
<p><code>+</code> is called an operator. R has the operators you would expect for for basic mathematics:</p>
<p><strong>Arithmetic operators</strong><br></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">operator</th>
<th style="text-align: left;">meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">+</td>
<td style="text-align: left;">plus</td>
</tr>
<tr class="even">
<td style="text-align: left;">-</td>
<td style="text-align: left;">minus</td>
</tr>
<tr class="odd">
<td style="text-align: left;">*</td>
<td style="text-align: left;">times</td>
</tr>
<tr class="even">
<td style="text-align: left;">/</td>
<td style="text-align: left;">divided by</td>
</tr>
<tr class="odd">
<td style="text-align: left;">^</td>
<td style="text-align: left;">exponent</td>
</tr>
</tbody>
</table>
<p><strong>Logical Operators</strong><br></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">operator</th>
<th style="text-align: left;">meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">==</td>
<td style="text-align: left;">exactly equal</td>
</tr>
<tr class="even">
<td style="text-align: left;">!=</td>
<td style="text-align: left;">not equal to</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&lt;</td>
<td style="text-align: left;">less than</td>
</tr>
<tr class="even">
<td style="text-align: left;">&lt;=</td>
<td style="text-align: left;">less than or equal to</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&gt;</td>
<td style="text-align: left;">greater than</td>
</tr>
<tr class="even">
<td style="text-align: left;">&gt;=</td>
<td style="text-align: left;">greater than or equal to</td>
</tr>
<tr class="odd">
<td style="text-align: left;">x|y</td>
<td style="text-align: left;">x or y</td>
</tr>
<tr class="even">
<td style="text-align: left;">x&amp;y</td>
<td style="text-align: left;">x and y</td>
</tr>
<tr class="odd">
<td style="text-align: left;">!x</td>
<td style="text-align: left;">not x</td>
</tr>
</tbody>
</table>
<p>Spaces can be used to make code easier to read.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> <span class="dv">2</span> <span class="sc">==</span> <span class="dv">4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section>
<section id="objects" class="level2">
<h2 class="anchored" data-anchor-id="objects">Objects</h2>
<section id="creating-objects" class="level3">
<h3 class="anchored" data-anchor-id="creating-objects">Creating Objects</h3>
<p>When you have certain values, data, plots, etc that you want to work with You can create objects (make assignments) in R with the assignment operator <code>&lt;-</code>:</p>
<p>All R statements where you create objects, assignment statements, have the same form:</p>
<pre><code>object_name &lt;- value</code></pre>
<p>When reading that code say “object name gets value” in your head.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="sc">*</span> <span class="dv">4</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12</code></pre>
</div>
</div>
<p>Once you have an object you can do other calculations with it.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">*</span> x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 144</code></pre>
</div>
</div>
<div class="shaded tip">
<p><strong>Objects vs.&nbsp;Variables</strong><br> What are known as objects in R are known as variables in many other programming languages. Depending on the context, object and variable can have drastically different meanings. However, in this lesson, the two words are used synonymously. For more information see: <a href="https://cran.r-project.org/doc/manuals/r-release/R-lang.html#Objects" class="uri">https://cran.r-project.org/doc/manuals/r-release/R-lang.html#Objects</a></p>
</div>
</section>
<section id="try-it-yourself" class="level3">
<h3 class="anchored" data-anchor-id="try-it-yourself">Try it Yourself!</h3>
<div class="callout callout-style-default callout-tip callout-titled" title="CHALLENGE">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
CHALLENGE
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Create an object with the value of your name</li>
<li>Create an object with the value of your age.</li>
</ol>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The exact answer will vary based on your information, but it should look something like:</p>
<ol type="1">
<li>my_name &lt;- “Jane”</li>
<li>my_age &lt;- 30</li>
</ol>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="working-with-objects" class="level3">
<h3 class="anchored" data-anchor-id="working-with-objects">Working with Objects</h3>
<p>That last example was kind of abstract. So let’s look at a more practical example.</p>
<p>Let’s do some calculations with the population of Maryland <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. First we can save the population number to an object. We will call it <code>md_pop</code> because that is short, descriptive, and easy to remember.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>md_pop <span class="ot">&lt;-</span> <span class="dv">6200000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>What percentage of the Maryland population are adults? According to the Census Bureau <a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>, 78% of the Maryland population is 18 and over. We can use that to calculate the number of adults in Maryland.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>md_adult_pop <span class="ot">&lt;-</span> .<span class="dv">78</span> <span class="sc">*</span> md_pop</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we want to know what percentage of people in Maryland have been fully vaccinated for COVID-19. As of early July 2022, when this lesson was first written, 4.68 million people of all ages had been fully vaccinated in Maryland <a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. So let’s create another object:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>md_vax_pop <span class="ot">&lt;-</span> <span class="dv">4680000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we can calculate the percentage of the Maryland population that was vaccinated at that time.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>percent_vax <span class="ot">&lt;-</span> (md_vax_pop <span class="sc">/</span> md_pop) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>percent_vax</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 75.48387</code></pre>
</div>
</div>
<p>The information in a variable can be updated as necessary. As of May 2023, when the CDC stopped extensively tracking COVID-19 vaccination information, 4.83 million people of all ages had been vaccinated in Maryland. We can re-assign the value of <code>md_vax_pop</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>md_vax_pop <span class="ot">&lt;-</span> <span class="dv">4830000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then recalculate <code>percent_vax</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>percent_vax <span class="ot">&lt;-</span> (md_vax_pop <span class="sc">/</span> md_pop) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>percent_vax</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 77.90323</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Tip">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>You will make lots of assignments and <code>&lt;-</code> is a pain to type. Avoid the temptation to use <code>=</code>: it will work, but it will cause confusion later. Instead, use RStudio’s keyboard shortcut: <kbd><code>Alt + -</code></kbd> (the minus sign).</p>
<p>Notice that RStudio automagically surrounds <code>&lt;-</code> with spaces, which is a good code formatting practice. Code is miserable to read on a good day, so giveyoureyesabreak and use spaces.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Naming Objects">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Naming Objects
</div>
</div>
<div class="callout-body-container callout-body">
<p>The name for objects must start with a letter, and can only contain letters, numbers, underscores (<code>_</code>)and periods (<code>.</code>). The name of the object should describe what is being assigned so they typically will be multiple words. One convention used is <strong>snake_case</strong> where lowercase words are separated with <code>_</code>. Another popular style is <strong>camelCase</strong> where compound words or phrases are written so that each word or abbreviation in the middle of the phrase begins with a capital letter, with no intervening spaces or punctuation and the first letter is lowercase.</p>
<pre><code>    thisIsCamelCase
    some_use_snake_case
    others.use.periods                  #avoid
    Others_pRefer.to_RENOUNCEconvention #avoid
</code></pre>
</div>
</div>
</section>
<section id="try-it-yourself-1" class="level3">
<h3 class="anchored" data-anchor-id="try-it-yourself-1">Try it Yourself!</h3>
<div class="callout callout-style-default callout-tip callout-titled" title="CHALLENGE">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
CHALLENGE
</div>
</div>
<div class="callout-body-container callout-body">
<p>Earlier you created an object called <code>md_adult_pop</code> which used Census data to calculate the number of adults living in Maryland. According to the CDC<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>, 4.17 million adults in Maryland had been fully vaccinated against COVID-19 as of May 2023.</p>
<ol type="1">
<li>Assign the number of fully vaccinated adults in Maryland to a new object.</li>
<li>Use the new object together with <code>md_adult_pop</code> to calculate the percentage of adults in Maryland who are fully vaccinated. Save this to an object called <code>md_adult_percent_vax</code>.</li>
</ol>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><code>md_adult_vax_pop &lt;- 4170000</code></li>
<li>`md_adult_percent_vax &lt;- (md_adult_vax_pop / md_adult_pop) * 100</li>
</ol>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="saving-code-in-an-r-script" class="level2">
<h2 class="anchored" data-anchor-id="saving-code-in-an-r-script">Saving code in an R script</h2>
<p>It might seem like you could just as easily calculate the percentage of vaccinated Marylanders by hand. But what if you had to do it again and again, multiple times a day, for days on end? What if you had to make sure multiple people on your team could perform the same task?</p>
<p>This is where the real strength of R as a programming language comes in. You can save all the steps of your analysis to a <em>script</em>. This is especially powerful if you have long and complicated analyses. It is how R contributes to reproducible and open science.</p>
<p>Open the file <code>vax_count.R</code>. Here we have recorded the steps we just took. So let’s say you were training a new employee to run this very important analysis. Now all they have to do is input the new vaccination number, and run the script.</p>
<p>The usual workflow is to save your code in an R script (“.R file”). Go to “File/New File/R Script” to create a new R script. Code in your R script can be sent to the console by selecting it or placing the cursor on the correct line, and then pressing <strong>Control-Enter</strong> (<strong>Command-Enter</strong> on a Mac).</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Add comments to code, using lines starting with the <code>#</code> character. This makes it easier for others to follow what the code is doing (and also for us the next time we come back to it).</p>
</div>
</div>
</section>
<section id="setting-your-working-directory" class="level2">
<h2 class="anchored" data-anchor-id="setting-your-working-directory">Setting your Working Directory</h2>
<p>The working directory is the directory ( or folder) which you are currently in, and from which any code you run will be executed. It’s important to know what directory you are working in, so your code runs predictably. For example, when working with data, you need to know how to tell the computer where that data file is located and where to save any output files. You’ll provide those locations in relationship to the working directory.</p>
<p>We can find out our current working directory with the function <code>getwd()</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "C:/Users/ayarnell/OneDrive - University of Maryland Baltimore/Desktop/intro-to-r"</code></pre>
</div>
</div>
<p>You can select a different working directory with the function <code>setwd()</code>. Let’s set our working directory to the <code>Session01</code> folder.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"~/Desktop/Session01_RBasics"</span>) <span class="co">#This path may vary based on exact computer set up.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Alternatively you can navigate to the desired working directory using the <code>Files</code> pane and set the working directory from there. Click the gear wheel for “More” within the RStudio file pane.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/workingDir01.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="246"></p>
</figure>
</div>
</div>
</div>
<p>Or by selecting the drop down list found in the Session menu at the top of the RStudio window.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/workingDir02.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="238"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="functions-and-their-arguments" class="level2">
<h2 class="anchored" data-anchor-id="functions-and-their-arguments">Functions and their arguments</h2>
<p><code>getwd()</code> and <code>setwd()</code> are examples of functions. Functions are “canned scripts” that automate more complicated sets of commands including operations assignments, etc. Many functions are predefined, or can be made available by importing R <em>packages</em> (more on that later). A function usually gets one or more inputs called <em>arguments</em>. Functions often (but not always) return a <em>value</em>.</p>
<p>A typical example would be the function <code>round()</code>. The input (the argument) must be a number, and the return value (in fact, the output) is that number rounded to the nearest whole number. Executing a function (‘running it’) is called <em>calling</em> the function. You can save the output of a function to an object. The format would look like:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">round</span>(a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here, the value of <code>a</code> is given to the <code>round()</code> function, the <code>round()</code> function rounds the number, and returns the value which is then assigned to the object <code>b</code>.</p>
<p>The return ‘value’ of a function need not be numerical (like that of <code>round()</code>), and it also does not need to be a single item: it can be a set of things, or even a dataset. We’ll see that when we read data files into R.</p>
<p>Arguments can be anything, not only numbers or file names, but also other objects. Exactly what each argument means differs per function, and must be looked up in the documentation (see below). Some functions take arguments which may either be specified by the user, or, if left out, take on a <em>default</em> value: these are called <em>options</em>. Options are typically used to alter the way the function operates, such as whether it ignores ‘bad values’, or what symbol to use in a plot. However, if you want something specific, you can specify a value of your choice which will be used instead of the default.</p>
<p><code>round()</code> only needs one argument, a number, or object that is storing a numerical value.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(percent_vax)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 78</code></pre>
</div>
</div>
<p>Here, we’ve called <code>round()</code> on our <code>percent_vax</code> object and it returned 78. That’s because the default action of the function is to round to the nearest whole number. If we want more digits we can see how to do that by getting information about the <code>round</code> function. We can use <code>args(round)</code> or look at the help for this function using <code>?round</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">args</span>(round)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>function (x, digits = 0, ...) 
NULL</code></pre>
</div>
</div>
<p>We see that if we want a different number of digits, we can type <code>digits=2</code> or however many we want.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(percent_vax, <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 77.9</code></pre>
</div>
</div>
<p>If you provide the arguments in the exact same order as they are defined you don’t have to name them:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(percent_vax, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 77.9</code></pre>
</div>
</div>
<p>And if you do name the arguments, you can switch their order:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="at">digits =</span> <span class="dv">2</span>, <span class="at">x =</span> percent_vax)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 77.9</code></pre>
</div>
</div>
<p>It’s good practice to put the non-optional arguments (like the number you’re rounding) first in your function call, and to specify the names of all optional arguments. If you don’t, someone reading your code might have to look up the definition of a function with unfamiliar arguments to understand what you’re doing.</p>
<section id="getting-help" class="level3">
<h3 class="anchored" data-anchor-id="getting-help">Getting Help</h3>
<p>In the previous example we looked up the arguments to <code>round()</code> using <code>args(round)</code> alternatively we couldve looked at the help page for <code>round()</code> to find this out with <code>?round</code>. To get help about a particular package or function you can access the help pane in RStudio and type its name in the search box.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/help.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>The <code>help()</code> function and <code>?</code> help operator in R provide access to the documentation pages for R functions, data sets, and other objects, both for packages in the standard R distribution and for contributed packages. To do so type as follows</p>
<pre><code>help({function})
help(package = {package name})

?{function}
?"{package name}"</code></pre>
</section>
<section id="try-it-yourself-2" class="level3">
<h3 class="anchored" data-anchor-id="try-it-yourself-2">Try it Yourself!</h3>
<div class="callout callout-style-default callout-tip callout-titled" title="CHALLENGE">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
CHALLENGE
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Create a new R script called <code>Exercises.R</code>. Save it to the Session01 folder (which should be your working directory). Use this file to answer any future challenge questions.</li>
<li>Use one of the strategies you learned in the <code>Getting Help</code> section to look at the documentation for the <code>seq</code> function. Use this documentation to figure out how to cgenerate the following sequence: <code>0 10 20 30 40 50 60 70 80 90 100</code></li>
</ol>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Go to <code>File &gt; New File &gt; R Script</code> at the top menu OR <code>CTRL + SHIFT + N</code> on the keyboard OR Select the icon with a green plus sign on a white rectangle in the ribbon OR From the Files pane go to <code>New File &gt; R Script</code></li>
<li><code>seq(from = 0, to = 100, by = 10)</code> OR <code>seq(from = 0, to = 100, length.out = 11)</code></li>
</ol>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="vectors" class="level2">
<h2 class="anchored" data-anchor-id="vectors">Vectors</h2>
<section id="what-is-a-vector" class="level3">
<h3 class="anchored" data-anchor-id="what-is-a-vector">What is a Vector?</h3>
<p><strong>“Vector”</strong> means different things in different fields (mathematics, geometry, biology), but in R it is a fancy name for a collection of values. We call the individual values <em>elements</em> of the vector. It is one of the most common data structures you will work with in R.</p>
<p>We can make vectors with the function <code>c( )</code>, for example <code>c(1,2,3)</code>. c means “combine”. R is obsessed with vectors, in R even single numbers are vectors of length one. Many things that can be done with a single number can also be done with a vector. For example arithmetic can be done on vectors as it can be on single numbers.</p>
</section>
<section id="working-with-vectors" class="level3">
<h3 class="anchored" data-anchor-id="working-with-vectors">Working with Vectors</h3>
<p>Let’s say that we have a group of patients in our clinic. (See info in patients_list.txt in the Session01 folder.) We can store their names in a vector.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>    patients <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Maria"</span>, <span class="st">"Jon"</span>, <span class="st">"Ali"</span>, <span class="st">"Luis"</span>, <span class="st">"Mei"</span> )</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    patients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Maria" "Jon"   "Ali"   "Luis"  "Mei"  </code></pre>
</div>
</div>
<p>If we later wanted to add a name, it’s easy to do so</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>patients <span class="ot">&lt;-</span> <span class="fu">c</span>(patients, <span class="st">"Emma"</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>patients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Maria" "Jon"   "Ali"   "Luis"  "Mei"   "Emma" </code></pre>
</div>
</div>
<p>Maybe we also want to store the weights of these patients. Since these are their weights in pounds, we will call our object <code>weight_lb</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>weight_lb <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">122</span>, <span class="dv">320</span>, <span class="dv">217</span>, <span class="dv">142</span>, <span class="dv">174</span>, <span class="dv">252</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>weight_lb</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 122 320 217 142 174 252</code></pre>
</div>
</div>
<p>So far, we have created vectors of two different <em>data types</em>: character and numeric.</p>
<p>You can do arithmetic with numeric vectors. For example, let’s convert the weight of our patients in lbs to the the weight in kilograms by multiplying each weight in lbs by 2.2.</p>
<p>We could do this one by one:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="dv">122</span> <span class="sc">/</span> <span class="fl">2.2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 55.45455</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="dv">320</span> <span class="sc">/</span> <span class="fl">2.2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 145.4545</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="dv">217</span> <span class="sc">/</span> <span class="fl">2.2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 98.63636</code></pre>
</div>
</div>
<p>etc.</p>
<p>But that would be a long and tedious process, especially if you had more than 6 patients.</p>
<p>Instead, let’s divide the vector by 2.2 and save that to a new object. We will call this object <code>weight_kg</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>weight_kg <span class="ot">&lt;-</span> weight_lb <span class="sc">/</span> <span class="fl">2.2</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="co">#you could also round the weight</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>weight_kg <span class="ot">&lt;-</span> <span class="fu">round</span>((weight_lb <span class="sc">/</span> <span class="fl">2.2</span>), <span class="at">digits =</span> <span class="dv">2</span>)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>weight_kg</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  55.45 145.45  98.64  64.55  79.09 114.55</code></pre>
</div>
</div>
<p>We could use the <code>mean()</code> function to find out the mean weight of patients at our clinic.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(weight_lb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 204.5</code></pre>
</div>
</div>
<p>You will not be able to perform calculations with character vectors.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>patients <span class="sc">+</span> <span class="st">"Sue"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in patients + "Sue": non-numeric argument to binary operator</code></pre>
</div>
</div>
<p>Remember we used <code>c()</code> to add a value to our character vector.</p>
<p>::: ::: {.callout-important title=“Data Types”}</p>
<p>There are numerous data types. Some of the other most common data types you will encounter are numeric data, character data and logical data. Vectors of one data type only are called <strong>atomic vectors</strong>. Read more about vectors and data types in the book <a href="https://r4ds.had.co.nz/vectors.html">R for Data Science</a></p>
<p>:::</p>
<p>Now let’s try working with some logical data. Logical data is the values<code>TRUE</code>, <code>FALSE</code>, or <code>NA</code></p>
<p>We want to record if our patients have been fully vaccinated. We will record this as TRUE if they have been, FALSE if they have not been, and NA if we do not have this information.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>vax_status <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>, <span class="cn">NA</span>, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>vax_status</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  TRUE  TRUE FALSE    NA  TRUE FALSE</code></pre>
</div>
</div>
<p>All vector types have a length property which you can determine with the <code>length()</code> function.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>    <span class="fu">length</span>(patients)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
</div>
<p>Its helpful to think of the length of a vector as the number of elements in the vector.</p>
<p>You can always find out the data type of your vector with the <code>class()</code> function.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(patients)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(weight_lb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(vax_status)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "logical"</code></pre>
</div>
</div>
</section>
<section id="try-it-yourself-3" class="level3">
<h3 class="anchored" data-anchor-id="try-it-yourself-3">Try it Yourself!</h3>
<div class="callout callout-style-default callout-tip callout-titled" title="CHALLENGE">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
CHALLENGE
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Create a vector of the following names: Marcia, Jan, Cindy. Assign this to an object called <code>brady_girls</code>.</li>
<li>Create another vector of the following names: Greg, Peter, Bobby. Assign this to an object called <code>brady_boys</code>.</li>
<li>Combine the <code>brady_girls</code> and <code>brady_boys</code> vectors together and assign to an object called <code>brady_bunch</code>.</li>
<li>Add the names Carol, Mike, and Alice to the <code>brady_bunch</code> vector</li>
</ol>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><code>brady_girls &lt;- c("Marcia", "Jan", "Cindy")</code></li>
<li><code>brady_boys &lt;- c("Greg", "Peter", "Bobby")</code></li>
<li><code>brady_bunch &lt;- c(brady_girls, brady_boys)</code></li>
<li><code>brady_bunch &lt;- c(brady_bunch, "Mike", "Carol", "Alice")</code></li>
</ol>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="missing-data" class="level3">
<h3 class="anchored" data-anchor-id="missing-data">Missing Data</h3>
<p>R also has many tools to help with missing data, a very common occurrence.</p>
<p>Suppose you tried to calculate the mean of a vector with some missing values (represented here with the logical <code>NA</code>. For example, what if we had failed to capture the weight of some of the patients at our clinic, so our weight vector looks as follows:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>missing_wgt <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">122</span>, <span class="cn">NA</span>, <span class="dv">217</span>, <span class="cn">NA</span>, <span class="dv">174</span>, <span class="dv">252</span>)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(missing_wgt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] NA</code></pre>
</div>
</div>
<p>The missing values cause an error, and the mean cannot be correctly calculated.</p>
<p>To get around this, you can use the argument <code>na.rm = TRUE</code>. This says to remove the NA values before attempting to perform the calculation.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(missing_wgt, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 191.25</code></pre>
</div>
</div>
<p>You can use the logical operator <code>is.na()</code> and it’s opposite <code>!is.na()</code> to check for NA values in your dataset. <code>is.na()</code> returns a logical vector of the same length as the original with a TRUE for every missing value and a FALSE for every value that is not missing,</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.na</span>(missing_wgt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE  TRUE FALSE  TRUE FALSE FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="sc">!</span><span class="fu">is.na</span>(missing_wgt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  TRUE FALSE  TRUE FALSE  TRUE  TRUE</code></pre>
</div>
</div>
<p>We can use the <code>sum()</code> function with <code>is.na()</code> to count up the number of missing values in our vector. This works because the computer understands TRUE as 1 and FALSE as 0.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(missing_wgt))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>For more on how to work with missing data, check out this <a href="https://datacarpentry.org/R-ecology-lesson/01-intro-to-r.html#Missing_data">Data Carpentry lesson</a></p>
</section>
<section id="mixing-data-types" class="level3">
<h3 class="anchored" data-anchor-id="mixing-data-types">Mixing Data Types</h3>
<p>We said above that vectors are supposed to have only one data type, but what happens if we mix multiple data types in one vector?</p>
<p>Sometimes the best way to understand R is to try some examples and see what it does.</p>
</section>
<section id="try-it-yourself-4" class="level3">
<h3 class="anchored" data-anchor-id="try-it-yourself-4">Try it Yourself!</h3>
<div class="callout callout-style-default callout-tip callout-titled" title="CHALLENGE">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
CHALLENGE
</div>
</div>
<div class="callout-body-container callout-body">
<p>What will happen in each of these examples? Pay attention to the resulting data type of each vector. Try running this code to see!</p>
<ol type="1">
<li><code>patient &lt;- c("Maria", 122, TRUE)</code></li>
<li><code>name_weight &lt;- c("John", 320, 145)</code></li>
<li><code>weight_status &lt;- c(217, 99, FALSE)</code></li>
</ol>
<p>Why do you think this happens?</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>All elements in the vector are turned to character data.</li>
<li>All elements in the vector are turned to character data</li>
<li>All elements in the vector are turned to numeric data.</li>
</ol>
<p>This process is called <em>coercion</em>. Because vectors can only contain one type of data, R chooses a lowest common denominator type of vector, a type that can contain everything we are trying to put in it. A different language might stop with an error, but R tries to soldier on as best it can. A number can be represented as a character string, but a character string can not be represented as a number, so when we try to put both in the same vector R converts everything to a character string. In the third example, we see that <code>FALSE</code> can be represented as numeric 0 (and `TRUE1, likewise can be represented as a 1).</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="indexing-and-subsetting-vectors" class="level3">
<h3 class="anchored" data-anchor-id="indexing-and-subsetting-vectors">Indexing and Subsetting vectors</h3>
<p>Access elements of a vector with <code>[ ]</code>, for example</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>    patients[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Maria"</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>    patients[<span class="dv">4</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Luis"</code></pre>
</div>
</div>
<p>You can use a colon <code>:</code> to access consecutive elements of a vector.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>patients[<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Jon"  "Ali"  "Luis"</code></pre>
</div>
</div>
<p>You can also assign to a specific element of a vector. We realize that we misspelled the name of our patient John, so we can overwrite our old value by assigning a new name to that element in our vector.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>    patients[<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="st">"John"</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>    patients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Maria" "John"  "Ali"   "Luis"  "Mei"   "Emma" </code></pre>
</div>
</div>
<p>Can we use a vector to index another vector? Yes!</p>
<p>Lets say we want to know which of our patients have been vaccinated. We know the vaccination status because we have a vector named <code>vax_status</code> lets look at it</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>vax_status</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  TRUE  TRUE FALSE    NA  TRUE FALSE</code></pre>
</div>
</div>
<p>Looking at the output we see the index of vaccinated people is elements <code>1, 2, and 5</code>. or where <code>vax_status</code> is <code>TRUE</code> in the output. We can use this numerical index to subset another from our vector <code>patients</code> which will give us a result that we’ll assign to a new object <code>vax_patients</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>    vaxInd <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">5</span>)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>    patients[vaxInd] <span class="co"># this line is saying patients[c(1,2,5)]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Maria" "John"  "Mei"  </code></pre>
</div>
</div>
<p>Now we can assign this vector to an object <code>vax_patients</code> to quickly look at our vaccinated patients.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>    vax_patients <span class="ot">&lt;-</span> patients[vaxInd]</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>    vax_patients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Maria" "John"  "Mei"  </code></pre>
</div>
</div>
<p>That was great! The problem with this approach is that if we’re in the real world and have a patient population of 1000 it will be really hard to go through our vax_status vector and see who has <code>vax_status</code> is <code>TRUE</code>. Fortunately there is a way to deal with this! Using conditional subsetting We could equivalently have written:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>    patients[vax_status <span class="sc">==</span> <span class="cn">TRUE</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Maria" "John"  NA      "Mei"  </code></pre>
</div>
</div>
<p>This output keeps the NA’s in there and that is not helpful since we only want to know who is vaccinated. Instead we can add a second condition! This condition is awesome because we can now show off our skills of working with missing data!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>patients[vax_status <span class="sc">==</span> <span class="cn">TRUE</span> <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(vax_status)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Maria" "John"  "Mei"  </code></pre>
</div>
</div>
<p>Another thing we can do is to assign our logical expression to an object so we can index our vector using it but also index other data structures like data frames which we are about to learn about. To do this would be like this:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># assign logical expression to an object</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>are_vaccinated <span class="ot">&lt;-</span> vax_status <span class="sc">==</span> <span class="cn">TRUE</span> <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(vax_status)</span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a><span class="co"># subset the vector according to the logical expression via using the object.</span></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>patients[are_vaccinated]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Maria" "John"  "Mei"  </code></pre>
</div>
</div>
</section>
<section id="try-it-yourself-5" class="level3">
<h3 class="anchored" data-anchor-id="try-it-yourself-5">Try it Yourself!</h3>
<div class="callout callout-style-default callout-tip callout-titled" title="CHALLENGE">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
CHALLENGE
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Use bracket notation to access the 4th element of the <code>brady_bunch</code> vector you created earlier.</li>
<li>Use bracket notation to access the 7th through 9th elements of hte <code>brady_bunch</code> vector.</li>
</ol>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><code>brady_bunch[4]</code></li>
<li><code>brady_bunch[7:9]</code> OR <code>brady_bunch[c(7,8,9)]</code></li>
</ol>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="data-frames-tibbles-and-exploring-data" class="level2">
<h2 class="anchored" data-anchor-id="data-frames-tibbles-and-exploring-data">Data frames, Tibbles, and Exploring Data</h2>
<p>Data frames are another VIP data structure in R. While vectors are one dimensional data structures. Data frames are two dimensional (often called tabular or rectangular data). This is similar to data as you might be used to seeing it in a spreadsheet. You can think of a data frame as consisting of columns of vectors. As vectors,each column in a data frame is of one data type, but the data frame over all can hold multiple data types.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/data-frame.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="240"></p>
</figure>
</div>
</div>
</div>
<p>A tibble is a particular class of data frame which is common in the <strong><code>tidyverse</code></strong> family of packages. Tibbles are useful for their printing properties and because they are less likely try to change the data type of columns on import (e.g.&nbsp;from character to factor).</p>
<section id="creating-data-frames" class="level3">
<h3 class="anchored" data-anchor-id="creating-data-frames">Creating data frames</h3>
<p>Data frames are usually created by reading in a dataset using the <code>read.table()</code> or <code>read.csv()</code> which we will cover in our next session. However, data frames can also be created explicitly with the <code>data.frame()</code> function or they can be coerced from other types of objects like lists. Now that we know vectors form the columns of data frames, we can take the vectors we created for our patient data and combine them together in a data frame.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>patient_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(patients, weight_lb, weight_kg, vax_status)</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>patient_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  patients weight_lb weight_kg vax_status
1    Maria       122     55.45       TRUE
2     John       320    145.45       TRUE
3      Ali       217     98.64      FALSE
4     Luis       142     64.55         NA
5      Mei       174     79.09       TRUE
6     Emma       252    114.55      FALSE</code></pre>
</div>
</div>
</section>
<section id="exploring-data-frames" class="level3">
<h3 class="anchored" data-anchor-id="exploring-data-frames">Exploring data frames</h3>
<p>Now we will look at ways to explore the contents of a data frame. For this part of the lesson we will use an object <code>variants</code>, a data frame, which is the <code>.rds</code> file in the data subfolder of your Session01 folder. To access this object locate <code>variants.rds</code> in the file viewer and click on it. In the dialog box that pops up select “OK” In the next session you will learn how to load data in to R but for now we have done this for you so you can focus on learning about exploring data frames.</p>
<p>The <code>variants</code> object is a dataset that comes from a real world experiment in E. Coli, you can find out more about the study in the <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4988878/">Tenaillon et al 2016</a> paper <a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>. The <code>variants</code> object is tabular version of a specialized genomics file type called a VCF file. VCF files are the output of a bioinformatics pipeline that starts with FASTQ files that come from a sequencer and ends with a VCF File. This pipeline typically happens outside of R and RStudio.</p>
<p>Your initial instinct with working with this object is to want to see it in a familiar spreadsheet form. The <code>View()</code> function gives us a spreadsheet-like view of the data frame.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(variants)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Using the <code>summary()</code> function and, we can learn a lot about the <code>variants</code> data frame including some summary statistics. Let’s examine what this function can tell us:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="do">## get summary statistics on a data frame</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(variants)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  sample_id            CHROM                POS             ID         
 Length:801         Length:801         Min.   :   1521   Mode:logical  
 Class :character   Class :character   1st Qu.:1115970   NA's:801      
 Mode  :character   Mode  :character   Median :2290361                 
                                       Mean   :2243682                 
                                       3rd Qu.:3317082                 
                                       Max.   :4629225                 
                                                                       
     REF                ALT                 QUAL          FILTER       
 Length:801         Length:801         Min.   :  4.385   Mode:logical  
 Class :character   Class :character   1st Qu.:139.000   NA's:801      
 Mode  :character   Mode  :character   Median :195.000                 
                                       Mean   :172.276                 
                                       3rd Qu.:225.000                 
                                       Max.   :228.000                 
                                                                       
   INDEL              IDV              IMF               DP       
 Mode :logical   Min.   : 2.000   Min.   :0.5714   Min.   : 2.00  
 FALSE:700       1st Qu.: 7.000   1st Qu.:0.8824   1st Qu.: 7.00  
 TRUE :101       Median : 9.000   Median :1.0000   Median :10.00  
                 Mean   : 9.396   Mean   :0.9219   Mean   :10.57  
                 3rd Qu.:11.000   3rd Qu.:1.0000   3rd Qu.:13.00  
                 Max.   :20.000   Max.   :1.0000   Max.   :79.00  
                 NA's   :700      NA's   :700                     
      VDB                 RPB              MQB              BQB        
 Min.   :0.0005387   Min.   :0.0000   Min.   :0.0000   Min.   :0.1153  
 1st Qu.:0.2180410   1st Qu.:0.3776   1st Qu.:0.1070   1st Qu.:0.6963  
 Median :0.4827410   Median :0.8663   Median :0.2872   Median :0.8615  
 Mean   :0.4926291   Mean   :0.6970   Mean   :0.5330   Mean   :0.7784  
 3rd Qu.:0.7598940   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000  
 Max.   :0.9997130   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  
                     NA's   :773      NA's   :773      NA's   :773     
      MQSB              SGB               MQ0F           ICB         
 Min.   :0.01348   Min.   :-0.6931   Min.   :0.00000   Mode:logical  
 1st Qu.:0.95494   1st Qu.:-0.6762   1st Qu.:0.00000   NA's:801      
 Median :1.00000   Median :-0.6620   Median :0.00000                 
 Mean   :0.96428   Mean   :-0.6444   Mean   :0.01127                 
 3rd Qu.:1.00000   3rd Qu.:-0.6364   3rd Qu.:0.00000                 
 Max.   :1.01283   Max.   :-0.4536   Max.   :0.66667                 
 NA's   :48                                                          
   HOB                AC          AN        DP4                  MQ       
 Mode:logical   Min.   :1   Min.   :1   Length:801         Min.   :10.00  
 NA's:801       1st Qu.:1   1st Qu.:1   Class :character   1st Qu.:60.00  
                Median :1   Median :1   Mode  :character   Median :60.00  
                Mean   :1   Mean   :1                      Mean   :58.19  
                3rd Qu.:1   3rd Qu.:1                      3rd Qu.:60.00  
                Max.   :1   Max.   :1                      Max.   :60.00  
                                                                          
    Indiv               gt_PL            gt_GT   gt_GT_alleles     
 Length:801         Min.   :   310   Min.   :1   Length:801        
 Class :character   1st Qu.:  1760   1st Qu.:1   Class :character  
 Mode  :character   Median :  2290   Median :1   Mode  :character  
                    Mean   :  3392   Mean   :1                     
                    3rd Qu.:  2550   3rd Qu.:1                     
                    Max.   :255156   Max.   :1                     
                                                                   </code></pre>
</div>
</div>
<p>The original dataset had 29 variables, so we get 29 fields to look at in the <code>summary()</code> output that summarize the data for each variable. The <code>QUAL</code>, <code>IMF</code>, and <code>VDB</code> variables (and several others) are numerical data and so you get summary statistics on the min and max values for these columns, as well as mean, median, and interquartile ranges. Many of the other variables (e.g.&nbsp;<code>sample_id</code>) are treated as characters data (more on this in a bit).</p>
<p>Running the name <code>variants</code> of the data frame in the console alone shows the first 10 rows, <code>print()</code> with the <code>n</code> argument can be used to show more than the first 10 rows on the console. Keep in mind this allows you to only see the number of variables that fit in the width of your console. So wider console window allows to see more variables.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(variants, <span class="at">n =</span> <span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If its the variable names you’re after you can do that with <code>names()</code> or <code>colnames()</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(variants) <span class="co"># you could also use names()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "sample_id"     "CHROM"         "POS"           "ID"           
 [5] "REF"           "ALT"           "QUAL"          "FILTER"       
 [9] "INDEL"         "IDV"           "IMF"           "DP"           
[13] "VDB"           "RPB"           "MQB"           "BQB"          
[17] "MQSB"          "SGB"           "MQ0F"          "ICB"          
[21] "HOB"           "AC"            "AN"            "DP4"          
[25] "MQ"            "Indiv"         "gt_PL"         "gt_GT"        
[29] "gt_GT_alleles"</code></pre>
</div>
</div>
<p>You have access to details about the number of columns and rows also:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co"># number of rows in variants</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(variants)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 801</code></pre>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co"># number of columns in variants</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(variants)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 29</code></pre>
</div>
</div>
<p><strong>Subsetting data frames</strong> Similar to subsetting vectors using bracket syntax <code>[]</code>, data frames can be subset using <code>[row,column]</code>. You can provide single dimensions to <code>row</code> and <code>column</code> or variations.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>variants[<span class="dv">4</span>, <span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  REF     
  &lt;chr&gt;   
1 CTTTTTTT</code></pre>
</div>
</div>
<p>While the output of this subset is a single value the output is considered a data frame. This is typical of tibbles.</p>
<p>You can use a column name (in quotes and literally the name of the variable) to subset instead of a number (numerical index):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>variants[<span class="dv">4</span>, <span class="st">"REF"</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  REF     
  &lt;chr&gt;   
1 CTTTTTTT</code></pre>
</div>
</div>
<p>The column or row may be omitted to retrieve the entire row or column.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>variants[<span class="dv">4</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 29
  sample_id  CHROM    POS ID    REF   ALT    QUAL FILTER INDEL   IDV   IMF    DP
  &lt;chr&gt;      &lt;chr&gt;  &lt;dbl&gt; &lt;lgl&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;lgl&gt;  &lt;lgl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 SRR2584863 CP00… 433359 NA    CTTT… CTTT…    64 NA     TRUE     12     1    12
# ℹ 17 more variables: VDB &lt;dbl&gt;, RPB &lt;dbl&gt;, MQB &lt;dbl&gt;, BQB &lt;dbl&gt;, MQSB &lt;dbl&gt;,
#   SGB &lt;dbl&gt;, MQ0F &lt;dbl&gt;, ICB &lt;lgl&gt;, HOB &lt;lgl&gt;, AC &lt;dbl&gt;, AN &lt;dbl&gt;, DP4 &lt;chr&gt;,
#   MQ &lt;dbl&gt;, Indiv &lt;chr&gt;, gt_PL &lt;dbl&gt;, gt_GT &lt;dbl&gt;, gt_GT_alleles &lt;chr&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a>variants[, <span class="st">"REF"</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 801 × 1
   REF                             
   &lt;chr&gt;                           
 1 T                               
 2 G                               
 3 G                               
 4 CTTTTTTT                        
 5 CCGC                            
 6 C                               
 7 C                               
 8 G                               
 9 ACAGCCAGCCAGCCAGCCAGCCAGCCAGCCAG
10 AT                              
# ℹ 791 more rows</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="co"># subset a range of rows using `colon :`</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>variants[<span class="dv">35</span><span class="sc">:</span><span class="dv">45</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 29
   sample_id CHROM    POS ID    REF   ALT    QUAL FILTER INDEL   IDV   IMF    DP
   &lt;chr&gt;     &lt;chr&gt;  &lt;dbl&gt; &lt;lgl&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;lgl&gt;  &lt;lgl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 SRR25848… CP00…  56613 NA    C     G       183 NA     FALSE    NA    NA    12
 2 SRR25848… CP00…  62118 NA    A     G       225 NA     FALSE    NA    NA    19
 3 SRR25848… CP00…  64042 NA    G     A       225 NA     FALSE    NA    NA    18
 4 SRR25848… CP00…  78808 NA    C     T       225 NA     FALSE    NA    NA    23
 5 SRR25848… CP00…  80113 NA    A     G       165 NA     FALSE    NA    NA     9
 6 SRR25848… CP00…  81158 NA    A     C       225 NA     FALSE    NA    NA    13
 7 SRR25848… CP00…  87462 NA    A     G       225 NA     FALSE    NA    NA    10
 8 SRR25848… CP00…  94370 NA    A     G       225 NA     FALSE    NA    NA    11
 9 SRR25848… CP00…  98286 NA    C     T       130 NA     FALSE    NA    NA     7
10 SRR25848… CP00…  98404 NA    G     A       225 NA     FALSE    NA    NA    14
11 SRR25848… CP00… 105581 NA    G     A       225 NA     FALSE    NA    NA    13
# ℹ 17 more variables: VDB &lt;dbl&gt;, RPB &lt;dbl&gt;, MQB &lt;dbl&gt;, BQB &lt;dbl&gt;, MQSB &lt;dbl&gt;,
#   SGB &lt;dbl&gt;, MQ0F &lt;dbl&gt;, ICB &lt;lgl&gt;, HOB &lt;lgl&gt;, AC &lt;dbl&gt;, AN &lt;dbl&gt;, DP4 &lt;chr&gt;,
#   MQ &lt;dbl&gt;, Indiv &lt;chr&gt;, gt_PL &lt;dbl&gt;, gt_GT &lt;dbl&gt;, gt_GT_alleles &lt;chr&gt;</code></pre>
</div>
</div>
<p>You can use a vector to retrieve specific rows or columns you may want. This vector can be a named object or created on the spot and passed as an argument in the subsetting.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>columns_desired <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,<span class="dv">6</span><span class="sc">:</span><span class="dv">7</span>, <span class="dv">9</span>)</span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>variants[, columns_desired] <span class="co"># same as variants[,c(1:3,6:7, 9)]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 801 × 6
   sample_id  CHROM          POS ALT                                  QUAL INDEL
   &lt;chr&gt;      &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;                               &lt;dbl&gt; &lt;lgl&gt;
 1 SRR2584863 CP000819.1    9972 G                                      91 FALSE
 2 SRR2584863 CP000819.1  263235 T                                      85 FALSE
 3 SRR2584863 CP000819.1  281923 T                                     217 FALSE
 4 SRR2584863 CP000819.1  433359 CTTTTTTTT                              64 TRUE 
 5 SRR2584863 CP000819.1  473901 CCGCGC                                228 TRUE 
 6 SRR2584863 CP000819.1  648692 T                                     210 FALSE
 7 SRR2584863 CP000819.1 1331794 A                                     178 FALSE
 8 SRR2584863 CP000819.1 1733343 A                                     225 FALSE
 9 SRR2584863 CP000819.1 2103887 ACAGCCAGCCAGCCAGCCAGCCAGCCAGCCAGCC…    56 TRUE 
10 SRR2584863 CP000819.1 2333538 ATT                                   167 TRUE 
# ℹ 791 more rows</code></pre>
</div>
</div>
<p>You might be interested in working with a new object that is just your subset from the main data frame. You can do this!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="co"># put the first three columns, column 6, column 7 and column 9 of variants into a new data frame called subset_variants</span></span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a>subset_variants <span class="ot">&lt;-</span> variants[,<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,<span class="dv">6</span><span class="sc">:</span><span class="dv">7</span>, <span class="dv">9</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Lets use <code>str()</code> to explore a bit more in depth how data frames work by looking at the “structure” of <code>subset_variants</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(subset_variants)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [801 × 6] (S3: tbl_df/tbl/data.frame)
 $ sample_id: chr [1:801] "SRR2584863" "SRR2584863" "SRR2584863" "SRR2584863" ...
 $ CHROM    : chr [1:801] "CP000819.1" "CP000819.1" "CP000819.1" "CP000819.1" ...
 $ POS      : num [1:801] 9972 263235 281923 433359 473901 ...
 $ ALT      : chr [1:801] "G" "T" "T" "CTTTTTTTT" ...
 $ QUAL     : num [1:801] 91 85 217 64 228 210 178 225 56 167 ...
 $ INDEL    : logi [1:801] FALSE FALSE FALSE TRUE TRUE FALSE ...</code></pre>
</div>
</div>
<p>Ok, thats a lot to unpack! Some things to notice.</p>
<p>In the output of <code>str()</code> we see the object type <code>tibble (S3: tbl_df/tbl/data.frame)</code> is displayed in the first row along with its dimensions <code>[801 × 6]</code>, in this case 801 observations (rows) and 6 variables (columns). Each variable (column) has a name (e.g.&nbsp;<code>sample_id</code>). This is followed by the object mode (e.g.&nbsp;<code>chr</code>, <code>num</code>, etc.). Notice that before each variable name there is a <code>$</code> - lets look at this a little more since this is another way we can subset.</p>
<p>So far we have used numbers to retrieve columns from our data frames however you might prefer using the column name. To use a name we can use <code>$</code> to retrieve columns. Occasionally it is also useful to use <code>[[ ]]</code> to retrieve columns, for example if the column name we want is stored in a variable.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extract the "ALT" column to a new object</span></span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a>alt_alleles <span class="ot">&lt;-</span> subset_variants<span class="sc">$</span>ALT</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Lets look at the first few elements of <code>alt_alleles</code> using <code>head()</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(alt_alleles)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "G"         "T"         "T"         "CTTTTTTTT" "CCGCGC"    "T"        </code></pre>
</div>
</div>
<p>This could have also been written using the double bracket notation</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>double_bracket_ALT <span class="ot">&lt;-</span> subset_variants[[<span class="st">"ALT"</span>]]</span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a><span class="co"># look at the first fiew rows of it</span></span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(double_bracket_ALT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "G"         "T"         "T"         "CTTTTTTTT" "CCGCGC"    "T"        </code></pre>
</div>
</div>
<p>To get the <code>ALT</code> value for row <code>4</code> we could use a mix of <code>$</code> and bracket <code>[]</code> subsetting.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a>subset_variants<span class="sc">$</span>ALT[<span class="dv">4</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "CTTTTTTTT"</code></pre>
</div>
</div>
<p>(you may notice at this point were using bracket notation on a vector because the output of a <code>$</code> subsetting is a vector, data frames are made up of columns of vectors!!!)</p>
<p><strong>Logical Subsetting(Indexing)</strong> We have already used logical indexing for subsetting a vector. Lets briefly look at an example of doing this with a data frame. Imagine that you want to have a data frame <code>subset_variants_low_qual</code> that is records from <code>subset_variants</code> that have very low quality scores.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a>low_qual_idX <span class="ot">&lt;-</span> subset_variants<span class="sc">$</span>QUAL <span class="sc">&lt;</span> <span class="dv">139</span></span>
<span id="cb126-2"><a href="#cb126-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-3"><a href="#cb126-3" aria-hidden="true" tabindex="-1"></a><span class="co"># take a peak at the head of this</span></span>
<span id="cb126-4"><a href="#cb126-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(low_qual_idX)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  TRUE  TRUE FALSE  TRUE FALSE FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="co"># how many are TRUE?</span></span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(low_qual_idX)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 200</code></pre>
</div>
</div>
<p><code>sum</code> treats <code>TRUE</code> as 1 and <code>FALSE</code> as 0, so it tells us the number of TRUE elements in the vector (<code>low_qual_idx</code>).</p>
<p>We can use this logical vector to get the subset data frame <code>subset_variants_low_qual</code> that is only variants below the threshold we set.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a>subset_variants_low_qual <span class="ot">&lt;-</span> subset_variants[low_qual_idX, ]</span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a><span class="co"># take a look at the subset confirming with the first few values that they are below the threshold</span></span>
<span id="cb130-3"><a href="#cb130-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(subset_variants_low_qual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  sample_id  CHROM          POS ALT                                   QUAL INDEL
  &lt;chr&gt;      &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;                                &lt;dbl&gt; &lt;lgl&gt;
1 SRR2584863 CP000819.1    9972 G                                     91   FALSE
2 SRR2584863 CP000819.1  263235 T                                     85   FALSE
3 SRR2584863 CP000819.1  433359 CTTTTTTTT                             64   TRUE 
4 SRR2584863 CP000819.1 2103887 ACAGCCAGCCAGCCAGCCAGCCAGCCAGCCAGCCA…  56   TRUE 
5 SRR2584863 CP000819.1 2407766 C                                    104   FALSE
6 SRR2584863 CP000819.1 2618472 T                                     31.9 FALSE</code></pre>
</div>
</div>
</section>
<section id="try-it-yourself-6" class="level3">
<h3 class="anchored" data-anchor-id="try-it-yourself-6">Try it Yourself!</h3>
<div class="callout callout-style-default callout-tip callout-titled" title="CHALLENGE">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
CHALLENGE
</div>
</div>
<div class="callout-body-container callout-body">
<p>For this exercise we will use a built-in R dataset called <code>ToothGrowth</code>. You can read more about built-in datasets by calling the code <code>library(help="datasets")</code></p>
<ol type="1">
<li>Use <code>head()</code> to look at the beginning of the dataset called <code>ToothGrowth</code>.</li>
<li>How would you find the number of columns and rows in <code>ToothGrowth</code>?</li>
<li>How would you find summary information about this dataset?</li>
<li>Use bracket notation to select the item in the 5th row and 2nd column of <code>ToothGrowth</code>.</li>
<li>Use bracket notation to select the 5th through 10th rows of <code>ToothGrowth</code>.</li>
<li>Use dollar sign notation to look at the <code>len</code> column of <code>ToothGrowth</code>.</li>
<li>Find the mean of the <code>len</code> column.</li>
<li>Use logical subsetting to save all the rows where the value in the <code>supp</code> column is <code>OJ</code>. Assign this to a new object.</li>
</ol>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><code>head(ToothGrowth)</code></li>
<li><code>ncol(ToothGrowth)</code> and <code>nrow(ToothGrowth)</code> OR <code>dim(ToothGrowth)</code> The data frame has 60 rows and 3 columns.</li>
<li><code>summary(ToothGrowth)</code></li>
<li><code>ToothGrowth[5,2]</code> . Should return <code>VC</code></li>
<li><code>ToothGrowth[5:10, ]</code></li>
<li><code>ToothGrowth$len</code></li>
<li><code>mean(ToothGrowth$len)</code></li>
<li><code>just_oj &lt;- ToothGrowth[ToothGrowth$supp == "OJ", ]</code></li>
</ol>
</div>
</div>
</div>
</div>
</div>
<p><strong>Introducing Factors</strong> Factors are the final major data type we will introduce in this R lessons. Factors can be thought of as vectors which are specialized for categorical data. Given R’s specialization for statistics, this make sense since categorical and continuous variables are usually treated differently. Sometimes you may want to have data treated as a factor, but in other cases, this may be undesirable.</p>
<p>To learn about factors we will work with the column <code>subset_variants$ALT</code>. First its important to know what type of object we’re working with using <code>typeof()</code> and then look at the first <code>15</code> elements of it using <code>head()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(subset_variants<span class="sc">$</span>ALT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(subset_variants<span class="sc">$</span>ALT, <span class="at">n =</span> <span class="dv">15</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "G"                                                       
 [2] "T"                                                       
 [3] "T"                                                       
 [4] "CTTTTTTTT"                                               
 [5] "CCGCGC"                                                  
 [6] "T"                                                       
 [7] "A"                                                       
 [8] "A"                                                       
 [9] "ACAGCCAGCCAGCCAGCCAGCCAGCCAGCCAGCCAGCCAGCCAGCCAGCCAGCCAG"
[10] "ATT"                                                     
[11] "C"                                                       
[12] "C"                                                       
[13] "T"                                                       
[14] "T"                                                       
[15] "A"                                                       </code></pre>
</div>
</div>
<p>There are 801 alleles (one for each row). To simplify, lets look at just the single-nuleotide alleles (SNPs). Before doing so we can confirm that SNPs are the most abundant using <code>table()</code>, we will also sort the output decreasing</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">table</span>(subset_variants<span class="sc">$</span>ALT), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
        A         T         G         C   GCCCCCC  GCCCCCCC  CAAAAAAA  TCCCCCCC 
      211       203       154       139         6         6         4         4 
CAAAAAAAA  TGGGGGGG 
        3         3 </code></pre>
</div>
</div>
<p>We can create a object <code>snps_variants</code> using another logical subsetting operator <code>%in%</code> that keeps rows corresponding to a vector of values in our case the values “A”, “C”, “G”, “T”.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a>snps_variants <span class="ot">&lt;-</span> subset_variants[subset_variants<span class="sc">$</span>ALT <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"C"</span>, <span class="st">"G"</span>, <span class="st">"T"</span>) ,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>When we look at <code>str()</code> did this make our object a factor?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(snps_variants<span class="sc">$</span>ALT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> chr [1:707] "G" "T" "T" "T" "A" "A" "C" "C" "T" "T" "A" "C" "A" "G" "C" ...</code></pre>
</div>
</div>
<p>NO! The output says <code>snps_variants$ALT</code> is a <code>chr</code> and we promised you factors! To turn this or any other character vector that should be a categorical variable into a factor we can use the function <code>factor()</code> lets do this and look at its structure again.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a>snps_variants<span class="sc">$</span>ALT <span class="ot">&lt;-</span> <span class="fu">factor</span>(snps_variants<span class="sc">$</span>ALT)</span>
<span id="cb141-2"><a href="#cb141-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(snps_variants<span class="sc">$</span>ALT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 4 levels "A","C","G","T": 3 4 4 4 1 1 2 2 4 4 ...</code></pre>
</div>
</div>
<p>What we get back are the categories (“A”,”C”,”G”,”T”) in our factor; these are called “Levels”. Levels are the different categories contained in a factor. For the sake of efficiency, R stores the content of a factor as a vector of integers, which an integer is assigned to each of the possible levels (a hold over from the old days when treating things as numbers saved space and processing time on the computer) By default, R will organize the levels in a factor in alphabetical order. So the first level in this factor is “A” and the final is “T”. We hope you have enjoyed this crash course in Factors! Now we will learn how to quickly explore our data with plots</p>
</section>
<section id="quickly-exploring-data-with-plots" class="level3">
<h3 class="anchored" data-anchor-id="quickly-exploring-data-with-plots">Quickly exploring data with plots</h3>
<p>For very quick exploration of data, it’s sometimes useful to use the plotting functions in base R. These are installed by default with R and do not require any additional packages to be installed. They’re quick to type, straightforward to use in simple cases, and run very quickly.</p>
<p>We will pick up with factors with our first example. One of the most common uses for factors will be when you plot categorical values. For example, suppose we want to know how many of our <code>snp_variants</code> had each possible SNP we could generate a plot:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(snps_variants<span class="sc">$</span>ALT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="01-RBasics_files/figure-html/unnamed-chunk-65-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>This isn’t a particularly pretty example of a plot but it works!</p>
<p>If you recall, factors are ordered alphabetically. That might make sense, but categories (e.g., “red”, “blue”, “green”) often do not have an intrinsic order. What if we wanted to order our plot according to the numerical value (i.e., in order of SNP frequency)? We can enforce an order on our factors and plot again!:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb144"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb144-1"><a href="#cb144-1" aria-hidden="true" tabindex="-1"></a>snps_variants<span class="sc">$</span>ordered_factor_snps <span class="ot">&lt;-</span> <span class="fu">factor</span>(snps_variants<span class="sc">$</span>ALT, <span class="at">levels =</span> <span class="fu">names</span>(<span class="fu">sort</span>(<span class="fu">table</span>(snps_variants<span class="sc">$</span>ALT))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s deconstruct this from the inside out (you can try each of these commands to see why this works):</p>
<ol type="1">
<li>We create a table of factor_snps to get the frequency of each SNP: <code>table(snps_variants$ALT)</code></li>
<li>We sort this table: <code>sort(table(snps_variants$ALT))</code>; use the decreasing = parameter for this function if you wanted to change from the default of FALSE</li>
<li>Using the names function gives us just the character names of the table sorted by frequencies:<code>names(sort(table(snps_variants$ALT)))</code></li>
<li>The <code>factor()</code> function is what allows us to create a factor. We give it the <code>snps_variants$ALT</code> object as input, and use the levels= parameter to enforce the ordering of the levels.</li>
</ol>
<p>Taking a look at the plot we see it is reordered and very easy on the eyes!:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(snps_variants<span class="sc">$</span>ordered_factor_snps)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="01-RBasics_files/figure-html/unnamed-chunk-67-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Wow! Adenine is the most frequent SNP in this data</p>
<p>If you want to make a quick histogram you can pass a vector of values to <code>hist()</code>. To specify an approximate number of bins instead of the default you can add a <code>breaks</code> argument.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb146"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb146-1"><a href="#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(variants<span class="sc">$</span>QUAL)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="01-RBasics_files/figure-html/unnamed-chunk-68-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get a clearer picture of the QUAL variable with more bins using `breaks=`</span></span>
<span id="cb147-2"><a href="#cb147-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb147-3"><a href="#cb147-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(variants<span class="sc">$</span>QUAL, <span class="at">breaks =</span> <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="01-RBasics_files/figure-html/unnamed-chunk-68-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>We have only covered 2 of the plots you can use to explore a dataset using Base R, we like these because they allow for quick checks of variables in the data. If you want to do anything beyond very simple plots, though, it’s generally better to switch to ggplot2 which you will learn in Session 3 of this series.</p>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Population data from <a href="https://www.census.gov/quickfacts/MD" class="uri">https://www.census.gov/quickfacts/MD</a><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Population data from <a href="https://www.census.gov/quickfacts/MD" class="uri">https://www.census.gov/quickfacts/MD</a><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Vaccination information from <a href="https://data.cdc.gov/Vaccinations/COVID-19-Vaccinations-in-the-United-States-County/8xkx-amqh" class="uri">https://data.cdc.gov/Vaccinations/COVID-19-Vaccinations-in-the-United-States-County/8xkx-amqh</a><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Centers for Disease Control and Prevention. COVID Data Tracker. Atlanta, GA: US Department of Health and Human Services, CDC; 2022, July 06. https://covid.cdc.gov/covid-data-tracker<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Tenaillon O, Barrick JE, Ribeck N, Deatherage DE, Blanchard JL, Dasgupta A, Wu GC, Wielgoss S, Cruveiller S, Médigue C, Schneider D, Lenski RE. Tempo and mode of genome evolution in a 50,000-generation experiment (2016) Nature. 536(7615): 165–170. Paper, Supplemental materials Data on NCBI SRA: https://trace.ncbi.nlm.nih.gov/Traces/sra/?study=SRP064605 Data on EMBL-EBI ENA: https://www.ebi.ac.uk/ena/data/view/PRJNA295606<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/hshsl-training\.github\.io\/intro-to-r\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://hshsl-training.github.io/intro-to-r/edit/main/01-RBasics.Rmd" class="toc-action"><i class="bi bi-git"></i>Edit this page</a></li><li><a href="https://hshsl-training.github.io/intro-to-r/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p><a href="https://creativecommons.org/licenses/by-sa/4.0/"><img src="https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by.svg" class="img-fluid" alt="CC BY" width="125"></a></p>
</div>
  </div>
</footer>




</body></html>