<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Wrangling with R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="https://www2.hshsl.umaryland.edu/cdabs/" class="navbar-brand navbar-brand-logo">
    <img src="https://www2.hshsl.umaryland.edu/hshsl/bin/img/logo_white@2x.png" alt="HSHSL logo" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./01-RBasics.html"> 
<span class="menu-text">R Basics</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./02-DataWrangling.html" aria-current="page"> 
<span class="menu-text">Data Wrangling</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./03-DataVisualization.html"> 
<span class="menu-text">Data Visualization</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#why-learn-r" id="toc-why-learn-r" class="nav-link" data-scroll-target="#why-learn-r">Why learn R?</a></li>
  <li><a href="#starting-out-in-r" id="toc-starting-out-in-r" class="nav-link" data-scroll-target="#starting-out-in-r">Starting out in R</a>
  <ul class="collapse">
  <li><a href="#downloading-installing-and-running-r" id="toc-downloading-installing-and-running-r" class="nav-link" data-scroll-target="#downloading-installing-and-running-r">Downloading, Installing and Running R</a></li>
  <li><a href="#rstudio" id="toc-rstudio" class="nav-link" data-scroll-target="#rstudio">RStudio</a></li>
  <li><a href="#rstudio-projects" id="toc-rstudio-projects" class="nav-link" data-scroll-target="#rstudio-projects">RStudio Projects</a></li>
  </ul></li>
  <li><a href="#r-scripts" id="toc-r-scripts" class="nav-link" data-scroll-target="#r-scripts">R Scripts</a></li>
  <li><a href="#welcome-to-the-tidyverse" id="toc-welcome-to-the-tidyverse" class="nav-link" data-scroll-target="#welcome-to-the-tidyverse">Welcome to the Tidyverse</a></li>
  <li><a href="#installing-and-loading-packages" id="toc-installing-and-loading-packages" class="nav-link" data-scroll-target="#installing-and-loading-packages">Installing and loading packages</a></li>
  <li><a href="#functions" id="toc-functions" class="nav-link" data-scroll-target="#functions">Functions</a></li>
  <li><a href="#what-is-tidy-data" id="toc-what-is-tidy-data" class="nav-link" data-scroll-target="#what-is-tidy-data">What is Tidy Data?</a></li>
  <li><a href="#the-data-for-this-lesson" id="toc-the-data-for-this-lesson" class="nav-link" data-scroll-target="#the-data-for-this-lesson">The Data for This Lesson</a></li>
  <li><a href="#importing-data" id="toc-importing-data" class="nav-link" data-scroll-target="#importing-data">Importing data</a></li>
  <li><a href="#exploring-and-summarizing-data" id="toc-exploring-and-summarizing-data" class="nav-link" data-scroll-target="#exploring-and-summarizing-data">Exploring and Summarizing data</a>
  <ul class="collapse">
  <li><a href="#vectors-and-data-frames-and-tibbles-oh-my" id="toc-vectors-and-data-frames-and-tibbles-oh-my" class="nav-link" data-scroll-target="#vectors-and-data-frames-and-tibbles-oh-my">Vectors and Data Frames and Tibbles oh my!</a></li>
  <li><a href="#base-r-functions-for-exploring-data" id="toc-base-r-functions-for-exploring-data" class="nav-link" data-scroll-target="#base-r-functions-for-exploring-data">Base R functions for exploring data</a></li>
  <li><a href="#tidyverse-functions-for-exploring-data" id="toc-tidyverse-functions-for-exploring-data" class="nav-link" data-scroll-target="#tidyverse-functions-for-exploring-data"><strong><code>tidyverse</code></strong> functions for exploring data</a></li>
  <li><a href="#try-it-yourself" id="toc-try-it-yourself" class="nav-link" data-scroll-target="#try-it-yourself">Try it Yourself!</a></li>
  </ul></li>
  <li><a href="#subsetting-data-with-select-and-filter" id="toc-subsetting-data-with-select-and-filter" class="nav-link" data-scroll-target="#subsetting-data-with-select-and-filter">Subsetting data with <code>select()</code> and <code>filter()</code></a>
  <ul class="collapse">
  <li><a href="#select" id="toc-select" class="nav-link" data-scroll-target="#select"><code>select()</code></a></li>
  <li><a href="#filter" id="toc-filter" class="nav-link" data-scroll-target="#filter"><code>filter()</code></a></li>
  <li><a href="#try-it-yourself-1" id="toc-try-it-yourself-1" class="nav-link" data-scroll-target="#try-it-yourself-1">Try it Yourself</a></li>
  </ul></li>
  <li><a href="#changing-and-creating-variables-with-mutate" id="toc-changing-and-creating-variables-with-mutate" class="nav-link" data-scroll-target="#changing-and-creating-variables-with-mutate">Changing and creating variables with <code>mutate()</code></a></li>
  <li><a href="#grouping-and-summarizing" id="toc-grouping-and-summarizing" class="nav-link" data-scroll-target="#grouping-and-summarizing">Grouping and Summarizing</a></li>
  <li><a href="#sorting-datasets-with-arrange" id="toc-sorting-datasets-with-arrange" class="nav-link" data-scroll-target="#sorting-datasets-with-arrange">Sorting datasets with <code>arrange()</code></a></li>
  <li><a href="#joining-datasets" id="toc-joining-datasets" class="nav-link" data-scroll-target="#joining-datasets">Joining Datasets</a></li>
  <li><a href="#long-vs-wide-formats" id="toc-long-vs-wide-formats" class="nav-link" data-scroll-target="#long-vs-wide-formats">Long vs Wide formats</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://hshsl-training.github.io/intro-to-r/edit/main/02-DataWrangling.qmd" class="toc-action"><i class="bi bi-git"></i>Edit this page</a></li><li><a href="https://hshsl-training.github.io/intro-to-r/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data Wrangling with R</h1>
<p class="subtitle lead">An Introduction to the Tidyverse</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<p>By the end of this session, students will be able to:</p>
<ul>
<li>Explain some benefits of learning R</li>
<li>Understand the difference between R and RStudio</li>
<li>Navigate RStudio</li>
<li>Define key R concepts and terminology.</li>
<li>Identify sources of documentation about R packages and functions</li>
<li>Apply commonly used <strong><code>tidyverse</code></strong> functions to a real data set</li>
<li>Becoming familiar with a typical workflow for exploring and wrangling data.</li>
</ul>
</section>
<section id="why-learn-r" class="level2">
<h2 class="anchored" data-anchor-id="why-learn-r">Why learn R?</h2>
<ul>
<li><p><strong>R is free, open-source, and cross-platform.</strong> Anyone can inspect the source code to see how R works. Because of this transparency, there is less chance for mistakes, and if you (or someone else) find some, you can report and fix bugs. Because R is open source and is supported by a large community of developers and users, there is a very large selection of third-party add-on packages which are freely available to extend R’s native capabilities.</p></li>
<li><p><strong>R code is great for reproducibility</strong>. Reproducibility is when someone else (including your future self) can obtain the same results from the same dataset when using the same analysis. R integrates with other tools to generate manuscripts from your code. If you collect more data, or fix a mistake in your dataset, the figures and the statistical tests in your manuscript are updated automatically.</p></li>
<li><p><strong>R relies on a series of written commands, not on remembering a succession of pointing and clicking.</strong> If you want to redo your analysis because you collected more data, you don’t have to remember which button you clicked in which order to obtain your results; you just have to run your script again.</p></li>
<li><p><strong>R is interdisciplinary and extensible</strong> With 10,000+ packages that can be installed to extend its capabilities, R provides a framework that allows you to combine statistical approaches from many scientific disciplines to best suit the analytical framework you need to analyze your data. For instance, R has packages for image analysis, GIS, time series, population genetics, and a lot more.</p></li>
<li><p><strong>R works on data of all shapes and sizes.</strong> The skills you learn with R scale easily with the size of your dataset. Whether your dataset has hundreds or millions of lines, it won’t make much difference to you. R is designed for data analysis. It comes with special data structures and data types that make handling of missing data and statistical factors convenient. R can connect to spreadsheets, databases, and many other data formats, on your computer or on the web.</p></li>
<li><p><strong>R produces high-quality graphics.</strong> The plotting functionalities in R are endless, and allow you to adjust any aspect of your graph to convey most effectively the message from your data.</p></li>
<li><p><strong>R has a large and welcoming community.</strong> Thousands of people use R daily. Many of them are willing to help you through mailing lists and websites such as <a href="https://stackoverflow.com/">Stack Overflow</a>, or on the <a href="https://community.rstudio.com/">RStudio community</a>. Questions which are backed up with <a href="https://www.tidyverse.org/help/">short, reproducible code snippets</a> are more likely to attract knowledgeable responses.</p></li>
</ul>
</section>
<section id="starting-out-in-r" class="level2">
<h2 class="anchored" data-anchor-id="starting-out-in-r">Starting out in R</h2>
<p><a href="https://cran.rstudio.com/">R</a> is both a programming language and an interactive environment for data exploration and statistics.</p>
<p>Working with R is primarily text-based. The basic mode of use for R is that the user provides commands in the R language and then R computes and displays the result.</p>
<section id="downloading-installing-and-running-r" class="level3">
<h3 class="anchored" data-anchor-id="downloading-installing-and-running-r">Downloading, Installing and Running R</h3>
<p><strong>Download</strong><br>
R can be downloaded from <a href="https://cran.rstudio.com/index.html">CRAN (The Comprehensive R Archive Network)</a> for Windows, Linux, or Mac.</p>
<p><strong>Install</strong><br>
Installation of R is like most software packages and you will be guided. Should you have any issues or need help you can refer to <a href="https://cran.r-project.org/doc/manuals/r-release/R-admin.html">R Installation and Administration</a></p>
<p><strong>Running</strong><br>
R can be launched from your software or applications launcher or When working at a command line on UNIX or Windows, the command <code>R</code> can be used for starting the main R program in the form <code>R</code></p>
<p>You will see a console similar to this appear:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="images/console.png" class="img-fluid figure-img" width="414"></p>
</figure>
</div>
</div>
</div>
<p>While it is possible to work solely through the console or using a command line interface, the ideal environment to work in R is RStudio.</p>
</section>
<section id="rstudio" class="level3">
<h3 class="anchored" data-anchor-id="rstudio">RStudio</h3>
<p><a href="https://www.rstudio.com/products/rstudio/download/">RStudio</a> is a user interface for working with R. It is called an Integrated Development Environment (IDE): a piece of software that provides tools to make programming easier. RStudio acts as a sort of wrapper around the R language. You can use R without RStudio, but it’s much more limiting. RStudio makes it easier to import datasets, create and write scripts, and makes using R much more effective. RStudio is also free and open source. To function correctly, RStudio needs R and therefore both need to be installed on your computer.</p>
<p>RStudio is divided into four “panes”. The placement of these panes and their content can be customized (see menu, Tools -&gt; Global Options -&gt; Pane Layout).</p>
<p>The Default Layout is:</p>
<ul>
<li>Top Left - <strong>Source</strong>: your scripts and documents</li>
<li>Bottom Left - <strong>Console</strong>: what R would look and be like without RStudio</li>
<li>Top Right - <strong>Environment/History</strong>: look here to see what you have done</li>
<li>Bottom Right - <strong>Files</strong> and more: see the contents of the project/working directory here, like your Script.R file</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="images/rstudio.png" class="img-fluid figure-img" width="1002"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="rstudio-projects" class="level3">
<h3 class="anchored" data-anchor-id="rstudio-projects">RStudio Projects</h3>
<p>RStudio provides a useful feature called <code>Projects</code> which act like a container for your work. As you use R more, you will find it useful to make sure your files and environment for one real-world project are kept together and separate from other projects.</p>
<p>Let’s create a new project now.</p>
<ol type="1">
<li>Go to <code>File &gt; New Project</code></li>
<li>In <code>Create project from</code> menu choose <code>Existing Directory</code></li>
<li>Browse to <code>Desktop &gt; Session01_DataWrangling</code></li>
<li>Select the check box that says <code>Open in New Session</code></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" data-appearence="minimal">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Follow Along at Home
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Posit (RStudio) Cloud is a browser-based version of RStudio. It will allow you to use RStudio without needing to download anything to your computer. Posit Cloud automatically organizes things into Projects. You can also easily share your R projects with others.</p>
<p>Get Started:</p>
<ol type="1">
<li>Create your free RStudio Cloud account at <a href="https://posit.cloud/plans/free" class="uri">https://posit.cloud/plans/free</a>.</li>
<li>Go to the class project <a href="https://posit.cloud/content/8458222" class="uri">https://posit.cloud/content/8458222</a></li>
<li>Note the text that marks this as a Temporary Copy. Select the <code>Save a Permanent Copy</code> button to begin working!</li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="r-scripts" class="level2">
<h2 class="anchored" data-anchor-id="r-scripts">R Scripts</h2>
<p>A script is a text file in which you write your code. R scripts are generally recognized by the <code>.R</code> file extension. Scripts make it easy to re-run that code when you need to. In addition to code, your script can also have comments, which start with a <code>#</code> symbol. These comments make your script more human readable, but are ignored by the computer.</p>
<p>To get started in this lesson - open up the script in your RStudio Project called <code>01_DataWrangling.R</code></p>
</section>
<section id="welcome-to-the-tidyverse" class="level2">
<h2 class="anchored" data-anchor-id="welcome-to-the-tidyverse">Welcome to the Tidyverse</h2>
<p>In this lesson, we will be using a group of packages which are part of what is known as the <strong><code>tidyverse</code></strong> - “an opinionated collection of R packages designed for data science. All packages share an underlying design philosophy, grammar, and data structures.”<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, developed by Hadley Wickham.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What is a package?
</div>
</div>
<div class="callout-body-container callout-body">
<p>As mentioned above, R is <em>extensible</em> and packages are the way to <em>extend</em> the base functionality of R. Each package is a collection of <strong>functions</strong>, code, data, and documentation. Packages are specialized to accomplish a particular set of tasks. Users can easily install packages from package repositories, such as the central repository <a href="https://cran.r-project.org/">CRAN</a> (Comprehensive R Archive Network) and <a href="https://www.bioconductor.org/">Bioconductor</a>, an important source of bioinformatics packages.</p>
<p>The sheer number of R packages can seem overwhelming to a beginner and a common question we hear is, “But how do I know what package to use?”. One place is to start is to take a look at <a href="https://cran.r-project.org/web/views/">CRAN Task Views</a>, which organizes packages by topic. You can also try an internet search like “How do I do X in R” and this will typically lead you to solutions that mention packages you need to accomplish the task.</p>
<p>One reason we are focusing on the <strong>tidyverse</strong> packages in this class is because they are so versatile and might be the only packages you need for much of what you want to do in R.</p>
</div>
</div>
<p>The <strong>tidyverse</strong> packages we will be using include:</p>
<ul>
<li><strong><code>readr</code></strong> for importing data into R</li>
<li><strong><code>dplyr</code></strong> for handling common data wrangling tasks for tabular data</li>
<li><strong><code>tidyr</code></strong> which enables you to swiftly convert between different data formats (long vs.&nbsp;wide) for plotting and analysis</li>
<li><strong><code>lubridate</code></strong> for working with dates</li>
<li><strong><code>ggplot2</code></strong> for visualizing data (we’ll explore this package in the next session).</li>
</ul>
<p>For the full list of tidyverse packages and documentation visit <a href="https://www.tidyverse.org/">tidyverse.org</a> You can install these packages individually, or you can install the entire tidyverse in one go.</p>
</section>
<section id="installing-and-loading-packages" class="level2">
<h2 class="anchored" data-anchor-id="installing-and-loading-packages">Installing and loading packages</h2>
<p>When you first install R on your computer, it comes with a set of built-in packages and functions collectively referred to as Base R. To add additional packages, you must first install that package, and then load it into your current session. If you are taking this workshop in person at the library, or using the <a href="https://posit.cloud/content/8458222">class Posit Cloud project</a>, the <strong><code>tidyverse</code></strong> has already been installed, so we just need to load it. You only need to install a package once on a system, but you will load it each time you start a new r session. If the package had not already been installed, we would install with a function called <code>install.packages()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install tidyverse if you haven't yet</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("tidyverse")</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">#load tidyverse</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="functions" class="level2">
<h2 class="anchored" data-anchor-id="functions">Functions</h2>
<p><code>install.packages()</code> and <code>library()</code> are two examples of <strong>functions</strong>. Functions are one of the most important components of R code. A function is like a canned script. It usually takes some inputs, called <strong>arguments</strong> inside the parentheses that follow the name of the function, performs one or more tasks, and often returns some kind of output. The <code>library()</code> function takes the name of the package to load as it’s argument.</p>
<p>How do you know what arguments a function takes? For that you need to turn to the documentation of a particular package, or from within RStudio you can look up a function with <code>?function-name</code>. Let’s try it with the <code>library()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>?library</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This opens the help pane in the lower right corner of RStudio. The documentation provides you with all the arguments and any default values, along with explanations of the arguments. Here we see that the the library function has the argument package with no defaults.</p>
</section>
<section id="what-is-tidy-data" class="level2">
<h2 class="anchored" data-anchor-id="what-is-tidy-data">What is Tidy Data?</h2>
<p>The <strong><code>tidyverse</code></strong> is so named from the concept of “tidy data”. Data is considered “tidy” if it follows three rules:</p>
<ol type="1">
<li>Each column is a variable</li>
<li>Each row is an observation</li>
<li>Each cell is a single value<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></li>
</ol>
<p>Data “in the wild” often isn’t tidy, but the tidyverse packages can help you create and analyze tidy datasets.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/tidy-data.PNG" class="img-fluid figure-img" width="960"></p>
<figcaption>tidy data structure<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="the-data-for-this-lesson" class="level2">
<h2 class="anchored" data-anchor-id="the-data-for-this-lesson">The Data for This Lesson</h2>
<p>For this lesson we will be using data which comes from <a href="https://www.tycho.pitt.edu/">Project Tycho</a> - an open data project from the University of Pittsburgh which provides standardized datasets on numerous diseases to aid global health research.</p>
<p>Throughout this lesson, we will be using a dataset from Project Tycho featuring historical counts of measles cases in the U.S.. We want to clean and present this data in a way that makes it easy to see how measles cases fluctuated over time.</p>
<p>A useful feature of Project Tycho data is their use of a common set of variables. Read more about their <a href="https://www.tycho.pitt.edu/dataformat/ProjectTychoPreCompiledDataFormat.pdf">data format</a>.</p>
</section>
<section id="importing-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-data">Importing data</h2>
<p>Now,that the <strong><code>tidyverse</code></strong> is loaded, we can use it to import some data into our RStudio session. We are using a function from the <strong><code>readr</code></strong> package called <code>read_csv()</code>. This function takes as an argument the path to where the file is located. Let’s start by reading in <code>measles_us</code> file in the <code>/data</code> folder.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_csv</span>(<span class="st">"data/measles_us.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 422051 Columns: 15
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (11): ConditionName, PathogenName, CountryName, CountryISO, Admin1Name, ...
dbl  (3): ConditionSNOMED, PartOfCumulativeCountSeries, CountValue
lgl  (1): DiagnosisCertainty

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 422,051 × 15
   ConditionName ConditionSNOMED PathogenName  CountryName CountryISO Admin1Name
   &lt;chr&gt;                   &lt;dbl&gt; &lt;chr&gt;         &lt;chr&gt;       &lt;chr&gt;      &lt;chr&gt;     
 1 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
 2 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
 3 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
 4 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
 5 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
 6 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
 7 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
 8 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
 9 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
10 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
# ℹ 422,041 more rows
# ℹ 9 more variables: Admin1ISO &lt;chr&gt;, Admin2Name &lt;chr&gt;, CityName &lt;chr&gt;,
#   PeriodStartDate &lt;chr&gt;, PeriodEndDate &lt;chr&gt;,
#   PartOfCumulativeCountSeries &lt;dbl&gt;, DiagnosisCertainty &lt;lgl&gt;,
#   SourceName &lt;chr&gt;, CountValue &lt;dbl&gt;</code></pre>
</div>
</div>
<p>But doing this just gives us a preview of the data in the console. To really use the data, we need to <strong>assign</strong> it to an <strong>object</strong>. An object is like a container for a numerical value, string, data set, image, and much more. Just about everything in R is an object. You might liken them to variables in other programming languages or in math. We create an object, by giving our data a name and use the <strong>assignment operator</strong>, which looks like an arrow <code>&lt;-</code>. You can manually type in the lesser than sign <code>&lt;</code> and hyphen <code>-</code>, or use the keyboard shortcut <code>Alt + -</code>.</p>
<p>Let’s call our new object <code>measles_us</code>. Object names should be short and easy to understand. They can’t have spaces, so you’ll want to separate multiple words with a underscore, or by using camel case. Object names also need to start with a letter not a number, and it’s best to avoid using names of common functions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>measles_us <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/measles_us.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>When you create an object, it shows up in your environment pane (the upper right panel). If we check our environment pane, we should now see an object called <code>measles_us</code>.</p>
<p>Let’s do the same for the <code>states.csv</code> file.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>states <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="at">file =</span> <span class="st">"data/states.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 50 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): name, division, region

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</section>
<section id="exploring-and-summarizing-data" class="level2">
<h2 class="anchored" data-anchor-id="exploring-and-summarizing-data">Exploring and Summarizing data</h2>
<p>Data wrangling, also known as data cleaning or data munging, involves preparing raw data for analysis by transforming it into a more useful format. This process includes detecting and correcting errors, handling missing values, and reorganizing data for analysis. Using the tidyverse, we can streamline these tasks efficiently. After importing the data, you’ll typically start by exploring it, identifying patterns, and making necessary adjustments to prepare it for visualization and further analysis. This foundational step ensures that your data is accurate, consistent, and ready for insightful exploration.</p>
<section id="vectors-and-data-frames-and-tibbles-oh-my" class="level3">
<h3 class="anchored" data-anchor-id="vectors-and-data-frames-and-tibbles-oh-my">Vectors and Data Frames and Tibbles oh my!</h3>
<p>First, it’s important to understand the type of object we just created. In R, tabular data like you find in a spreadsheet is stored in a <strong>data frame</strong>, one of the fundamental <strong>data structures</strong> in R. A data frame is a rectangular, two-dimensional data structure. That is, it has both columns and rows. Data frames can store multiple <strong>data types</strong>, such as numeric, character, and logical data, also known as classes.</p>
<p>A <strong>tibble</strong> is a tidyverse version of the standard R data frame. For our purposes, the differences are minor enough that we can generally use the terms interchangeably, but to be precise, we will be working with tibbles in this lesson. All tibbles are data frames, but not all data frames are tibbles.</p>
<p>Another important R data structure is a <strong>vector</strong>. A vector is a one-dimensional data structure. That is, it is simply a sequence of elements. A vector can have only one data type. Data frames are created from multiple vectors, that is, each column in a data frame is a vector of the same length.</p>
</section>
<section id="base-r-functions-for-exploring-data" class="level3">
<h3 class="anchored" data-anchor-id="base-r-functions-for-exploring-data">Base R functions for exploring data</h3>
<p><code>View()</code> opens the data as a file in your documents pane.This is a good way to see the data in a familiar spreadsheet-like format.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(measles_us)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Use <code>summary()</code> to look at each column and find the data type and interquartile range for numeric data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(measles_us)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Missing data">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Missing data
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Sometimes we get data with a large number of missing values. It can be helpful to know where data is missing before attempting to do any further analysis. R uses NA to indicate missing values. We can use the function <code>is.na()</code> to test for the presence of NAs in our data.<code>is.na()</code> will return a vector of values TRUE or FALSE. TRUE if the value is NA, FALSE if it is not. When we examined our data with the View function, we might have noticed that the first several values in Admin2Name column are missing (NA). We might want to know how many missing values total are in that column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.na</span>(measles_us<span class="sc">$</span>Admin2Name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After running this code you should see <code>TRUE</code> printed out repeatedly in the console. R is running through that column and printing TRUE whenever it runs into a missing value. But this still does not help us get the total number of NAs. To do that we need to nest the above code in another function <code>sum()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(measles_us<span class="sc">$</span>Admin2Name))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 198104</code></pre>
</div>
</div>
<p><code>sum()</code> treats each each TRUE as a 1 and each FALSE as a 0. In that column there are 198104 out of 422051</p>
<p>But, if you have a lot of variables (columns), it would be a pain to do this for each one. So instead we can use a similar function <code>colSums</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(measles_us))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              ConditionName             ConditionSNOMED 
                          0                           0 
               PathogenName                 CountryName 
                          0                           0 
                 CountryISO                  Admin1Name 
                          0                           0 
                  Admin1ISO                  Admin2Name 
                          0                      198104 
                   CityName             PeriodStartDate 
                     198104                           0 
              PeriodEndDate PartOfCumulativeCountSeries 
                          0                           0 
         DiagnosisCertainty                  SourceName 
                     422051                           0 
                 CountValue 
                          0 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="tidyverse-functions-for-exploring-data" class="level3">
<h3 class="anchored" data-anchor-id="tidyverse-functions-for-exploring-data"><strong><code>tidyverse</code></strong> functions for exploring data</h3>
<p>The <code>glimpse()</code> function which is part of the <strong><code>tidyverse</code></strong> package <strong><code>tibble</code></strong>, lets you see the column names and data types clearly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(measles_us)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>distinct()</code> returns the distinct rows in a tibble. It can be used on a column to return the distinct values in that column. The first argument you supply is the tibble object. Subsequent arguments include the variables you want to count.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">distinct</span>(measles_us, ConditionName)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  ConditionName
  &lt;chr&gt;        
1 Measles      </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">distinct</span>(measles_us, Admin1Name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 56 × 1
   Admin1Name
   &lt;chr&gt;     
 1 WISCONSIN 
 2 OHIO      
 3 MICHIGAN  
 4 NEVADA    
 5 NEW JERSEY
 6 WASHINGTON
 7 DELAWARE  
 8 KENTUCKY  
 9 WYOMING   
10 INDIANA   
# ℹ 46 more rows</code></pre>
</div>
</div>
<p><code>count()</code> is similar to <code>distinct()</code> but also returns the number of observations (i.e.&nbsp;rows) for each of those distinct values. The first argument you supply is the tibble object. Subsequent arguments include the variables you want to count.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">count</span>(measles_us, Admin1Name) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 56 × 2
   Admin1Name               n
   &lt;chr&gt;                &lt;int&gt;
 1 ALABAMA               7458
 2 ALASKA                1869
 3 AMERICAN SAMOA         118
 4 ARIZONA               4685
 5 ARKANSAS              5643
 6 CALIFORNIA           14354
 7 COLORADO              8042
 8 CONNECTICUT          10816
 9 DELAWARE              4507
10 DISTRICT OF COLUMBIA  5027
# ℹ 46 more rows</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Make code flow with the pipe %>%">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Make code flow with the pipe %&gt;%
</div>
</div>
<div class="callout-body-container callout-body">
<p>Before we go any further - I want to introduce you to an important time-saving symbol in R called the pipe <code>%&gt;%</code> (<code>CTRL + SHIFT + M</code>). The pipe allows you to take the output of the left-hand expression and make it the input of the right-hand expression. It allows you to chain together multiple functions and avoid nesting. With the pipe, we can rewrite the above code as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>measles_us <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Admin1Name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 56 × 2
   Admin1Name               n
   &lt;chr&gt;                &lt;int&gt;
 1 ALABAMA               7458
 2 ALASKA                1869
 3 AMERICAN SAMOA         118
 4 ARIZONA               4685
 5 ARKANSAS              5643
 6 CALIFORNIA           14354
 7 COLORADO              8042
 8 CONNECTICUT          10816
 9 DELAWARE              4507
10 DISTRICT OF COLUMBIA  5027
# ℹ 46 more rows</code></pre>
</div>
</div>
<p>In many tidyverse functions, the first argument is the name of the data frame you’re applying the function to. So when you use the pipe, you’ll generally start a line of code with the name of a tibble. One benefit you might notice right away, is that when we use the pipe, RStudio will supply the column names which helps to reduce typing and typos.</p>
</div>
</div>
</section>
<section id="try-it-yourself" class="level3">
<h3 class="anchored" data-anchor-id="try-it-yourself">Try it Yourself!</h3>
<div class="callout callout-style-default callout-tip callout-titled" title="CHALLENGE">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
CHALLENGE
</div>
</div>
<div class="callout-body-container callout-body">
<p>Now let’s try exploring the <code>states</code> tibble in our environment</p>
<ol type="1">
<li>Use <code>glimpse()</code> to inspect the columns and data types in the dataset.</li>
<li>Use <code>distinct()</code> to find out the distinct values in the <code>region</code> column.</li>
<li>Using <code>count()</code>, find out how many states are in each region.</li>
<li>Using <code>count()</code>, find out how many states are in each region AND division. HINT: You can add additional column names to <code>distinct()</code> and <code>count()</code> to look at combinations of columns.</li>
</ol>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><code>glimpse(states)</code></li>
<li><code>states %&gt;% distinct(region)</code></li>
<li><code>states %&gt;% count(region)</code></li>
<li><code>states %&gt;% count(region, division)</code></li>
</ol>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="subsetting-data-with-select-and-filter" class="level2">
<h2 class="anchored" data-anchor-id="subsetting-data-with-select-and-filter">Subsetting data with <code>select()</code> and <code>filter()</code></h2>
<p>Real data sets can be quite large. So, once you’ve explored your data, you may want to start trimming it down to just the variables and conditions you’re interested in. In this section, we’ll look at two functions from the <strong><code>tidyverse</code></strong> package called <strong><code>dplyr</code></strong>: <code>select()</code> which lets you choose columns (variables) and <code>filter()</code> which lets you choose rows. (Note: <code>dplyr</code> is known for using easy to understand verbs for its function names.)</p>
<section id="select" class="level3">
<h3 class="anchored" data-anchor-id="select"><code>select()</code></h3>
<p><code>select()</code> lets you choose columns by name. The syntax of this function is similar to the the ones we’ve already learned <code>count()</code> and <code>distinct()</code>. We need to supply the function with the name of the tibble and the columns. This will create a new tibble with just those columns.</p>
<p>As with all tidyverse functions, we can use <code>%&gt;%</code> to make this easier.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>measles_us <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(Admin1Name, CountValue)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 422,051 × 2
   Admin1Name CountValue
   &lt;chr&gt;           &lt;dbl&gt;
 1 WISCONSIN          85
 2 WISCONSIN         120
 3 WISCONSIN          84
 4 WISCONSIN         106
 5 WISCONSIN          39
 6 WISCONSIN          45
 7 WISCONSIN          28
 8 WISCONSIN         140
 9 WISCONSIN          48
10 WISCONSIN          85
# ℹ 422,041 more rows</code></pre>
</div>
</div>
<p>If you want to select several columns that are next to each other, you can use <code>:</code> to specify a range, rather than writing each name out separately.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>measles_us <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>( ConditionName<span class="sc">:</span>Admin1ISO)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 422,051 × 7
   ConditionName ConditionSNOMED PathogenName  CountryName CountryISO Admin1Name
   &lt;chr&gt;                   &lt;dbl&gt; &lt;chr&gt;         &lt;chr&gt;       &lt;chr&gt;      &lt;chr&gt;     
 1 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
 2 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
 3 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
 4 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
 5 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
 6 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
 7 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
 8 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
 9 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
10 Measles              14189004 Measles virus UNITED STA… US         WISCONSIN 
# ℹ 422,041 more rows
# ℹ 1 more variable: Admin1ISO &lt;chr&gt;</code></pre>
</div>
</div>
<p>Now, let’s think through which columns we want for our analysis and save this to a new object called <code>measles_select</code>. It’s always a good idea to create new objects when you make major changes to your data.</p>
<p>For this exercise, we want to look at trends in number of measles cases over time. To do that, we’ll need to keep our <code>CountValue</code> variable, as and the date variables (<code>PeriodStartDate</code> and <code>PeriodEndDate</code>), as well as the <code>PartOfCumulativeCountSeries</code> variable, which will help us understand how to use the dates (more on this later). The first five columns each have only one value. So it might be redundant to keep those, although if we were combining them with other Project Tycho datasets they could be useful. It might be interesting to get a state-level view of the data, so let’s keep <code>Admin1Name</code>. But we saw that there are a number of missing values in our <code>Admin2Name</code> and <code>CityName</code> variables, so they might not be very useful for our analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>measles_select <span class="ot">&lt;-</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  measles_us <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>     Admin1Name,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>     PeriodStartDate,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>     PeriodEndDate,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>     PartOfCumulativeCountSeries,</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>     CountValue</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Sometimes when receive a data set or start working with data, you may find that the column names are overly long or not very descriptive or useful, and it may be necessary to rename them. For this, we can use the <code>rename()</code> function. Like naming objects, you should use a simple, descriptive, relatively short name without spaces for your column names. Let’s rename <code>Admin1Name</code> to <code>State</code> to make that more meaningful to us. <code>rename()</code> has the syntax <code>rename(newColumnName = OldColumnName)</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>measles_select <span class="ot">&lt;-</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  measles_select <span class="sc">%&gt;%</span> </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">state =</span> Admin1Name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that in this case, we are overwriting our original object with the new name instead of creating a new one!</p>
</section>
<section id="filter" class="level3">
<h3 class="anchored" data-anchor-id="filter"><code>filter()</code></h3>
<p>While <code>select()</code> acts on columns, <code>filter()</code> acts on rows. <code>filter()</code> takes the name of the tibble and one or more logical conditions as arguments.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>measles_md <span class="ot">&lt;-</span> measles_select <span class="sc">%&gt;%</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(state <span class="sc">==</span> <span class="st">"MARYLAND"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here we are saying keep all the rows where the value in the <code>state</code> column is “MARYLAND”. Note the use of the double equals sign == versus the singular = sign. The double equal sign is a <strong>logical operator</strong>. The logical operators are:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>operator</th>
<th>meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>==</td>
<td>exactly equal</td>
</tr>
<tr class="even">
<td>!=</td>
<td>not equal to</td>
</tr>
<tr class="odd">
<td>&lt;</td>
<td>less than</td>
</tr>
<tr class="even">
<td>&lt;=</td>
<td>less than or equal to</td>
</tr>
<tr class="odd">
<td>&gt;</td>
<td>greater than</td>
</tr>
<tr class="even">
<td>&gt;=</td>
<td>greater than or equal to</td>
</tr>
<tr class="odd">
<td>x|y</td>
<td>x or y</td>
</tr>
<tr class="even">
<td>x&amp;y</td>
<td>x and y</td>
</tr>
<tr class="odd">
<td>!x</td>
<td>not x</td>
</tr>
</tbody>
</table>
<p>Note that after running our code, our resulting tibble (our new object <code>measles_md</code>) has 7246 observations (rows) while our original tibble had 422051.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>When matching strings you must be exact. R is case-sensitive. So <code>state == "Maryland"</code> or <code>state == "maryland"</code> would return 0 rows.</p>
</div>
</div>
<p>You can add additional conditions to filter by, separated other logical operators like <code>&amp;</code>, <code>&gt;</code>, and <code>&gt;</code>.</p>
<p>Below we want just the rows for Maryland, and only include periods where the count was more than 500 reported cases. Note that while you need quotation marks around character data, you do not need them around numeric data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>measles_select <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(state <span class="sc">==</span> <span class="st">"MARYLAND"</span> <span class="sc">&amp;</span> CountValue <span class="sc">&gt;</span> <span class="dv">500</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 328 × 5
   state    PeriodStartDate PeriodEndDate PartOfCumulativeCountSeries CountValue
   &lt;chr&gt;    &lt;chr&gt;           &lt;chr&gt;                               &lt;dbl&gt;      &lt;dbl&gt;
 1 MARYLAND 1/29/1928       2/4/1928                                0        504
 2 MARYLAND 2/5/1928        2/11/1928                               0        563
 3 MARYLAND 2/12/1928       2/18/1928                               0        696
 4 MARYLAND 2/19/1928       2/25/1928                               0        750
 5 MARYLAND 2/26/1928       3/3/1928                                0       1012
 6 MARYLAND 3/4/1928        3/10/1928                               0        951
 7 MARYLAND 3/11/1928       3/17/1928                               0       1189
 8 MARYLAND 3/18/1928       3/24/1928                               0       1163
 9 MARYLAND 3/25/1928       3/31/1928                               0       1020
10 MARYLAND 4/1/1928        4/7/1928                                0        753
# ℹ 318 more rows</code></pre>
</div>
</div>
<p>Here, we joined together 2 conditions with the <code>&amp;</code> logical operator. Then we <strong>piped</strong> that resulting tibble to <code>count()</code> which remember takes a tibble as its first argument.</p>
<p>What if we wanted to filter our tibble to include just the 50 states and no territories? We sure would not have to write out an expression for each state, or even all the territories.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we can avoid verbose code like this with %in%</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>measles_select <span class="sc">%&gt;%</span> </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(state <span class="sc">==</span> <span class="st">"MARYLAND"</span> <span class="sc">&amp;</span> state <span class="sc">==</span> <span class="st">"DELAWARE"</span> <span class="sc">&amp;</span> state <span class="sc">==</span> <span class="st">"Pennsylvania"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 5
# ℹ 5 variables: state &lt;chr&gt;, PeriodStartDate &lt;chr&gt;, PeriodEndDate &lt;chr&gt;,
#   PartOfCumulativeCountSeries &lt;dbl&gt;, CountValue &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Luckily, We can filter based on a vector of values with the <code>%in%</code> operator (remember we can think of a vector as a column of data). So, we can write some code to filter our data based on list of state names in our <code>states</code> tibble.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>measles_states_only <span class="ot">&lt;-</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  measles_select <span class="sc">%&gt;%</span> </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(state <span class="sc">%in%</span> states<span class="sc">$</span>name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s save this output to a new object <code>measles_states_only</code>. Notice how we now have fewer rows than we had in our <code>measles_select</code> object.</p>
<p>We could alternatively have used negation with the names of the values we specifically wanted to exclude.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>measles_states_only <span class="ot">&lt;-</span> measles_select <span class="sc">%&gt;%</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>state <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"PUERTO RICO"</span>, <span class="st">"GUAM"</span>, <span class="st">"AMERICAN SAMOA"</span>, <span class="st">"NORTHERN MARIANA ISLANDS"</span>, <span class="st">"VIRGIN ISLANDS, U.S."</span>, <span class="st">"DISTRICT OF COLUMBIA"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Great! Our dataset is really shaping up. Let’s also take a closer look at our date columns. If you look at the first several rows, it looks like each row of our dataset represents about a discrete week of measles case counts. But (as you can read in the Tycho data documentation) there are actually two date series in this dataset - non-cumulative and cumulative. Which series a row belongs to is noted by the <code>PartofCumulativeCountSeries</code>, which as the value <code>0</code> if a row is non-cumulative, and <code>1</code> if the row is part of a cumulative count.</p>
<p>To keep things consistent. Let’s filter our tibble so we only have the non-overlapping discrete weeks.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>measles_non_cumulative <span class="ot">&lt;-</span> </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  measles_states_only <span class="sc">%&gt;%</span> </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(PartOfCumulativeCountSeries<span class="sc">==</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once again, we have fewer rows than we started with.</p>
</section>
<section id="try-it-yourself-1" class="level3">
<h3 class="anchored" data-anchor-id="try-it-yourself-1">Try it Yourself</h3>
<div class="callout callout-style-default callout-tip callout-titled" title="CHALLENGE">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
CHALLENGE
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Use <code>select()</code> to create a new tibble with just the <code>name</code> and <code>division</code> columns from the <code>states</code> tibble. Assign this to an object called <code>us_divisions</code>.</li>
<li>Use <code>filter()</code> to keep just the rows in the <code>South Atlantic</code> division of the <code>us_divisions</code> tibble. Assign this to an object called <code>sa_division</code>.</li>
<li>Use <code>filter()</code> to keep just the rows in the <code>measles_non_cumulative</code> tibble where the <code>state</code> matches one of the states in the <code>name</code> column of the <code>sa_division</code> tibble and where the <code>CountValue</code> is greater than 1000. Assign this to an object called <code>measles_sa</code>.</li>
</ol>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><code>us_divisions &lt;- states %&gt;% select(name, division)</code></li>
<li><code>sa_division &lt;- us_divisions %&gt;% filter(division == "South Atlantic")</code></li>
<li><code>measles_sa &lt;- measles_non_cumulative %&gt;% filter(state %in% sa_division$name &amp; CountValue &gt; 1000)</code></li>
</ol>
</div>
</div>
</div>
</div>
</div>
<p>Now let’s do some more with our date variables.</p>
</section>
</section>
<section id="changing-and-creating-variables-with-mutate" class="level2">
<h2 class="anchored" data-anchor-id="changing-and-creating-variables-with-mutate">Changing and creating variables with <code>mutate()</code></h2>
<p>Let’s review the columns in our <code>measles_states_only</code> tibble</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(measles_non_cumulative)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 332,138
Columns: 5
$ state                       &lt;chr&gt; "WISCONSIN", "WISCONSIN", "WISCONSIN", "WI…
$ PeriodStartDate             &lt;chr&gt; "11/20/1927", "11/27/1927", "12/4/1927", "…
$ PeriodEndDate               &lt;chr&gt; "11/26/1927", "12/3/1927", "12/10/1927", "…
$ PartOfCumulativeCountSeries &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ CountValue                  &lt;dbl&gt; 85, 120, 84, 106, 39, 45, 28, 140, 48, 85,…</code></pre>
</div>
</div>
<p>We can see from this that the dates are being interpreted as <em>character</em> data. We want R to recognize them as dates. We can create new variables and adjust existing variables with the <code>mutate()</code> function.</p>
<p><code>mutate()</code> takes as an argument the name and definition of the new column you’re creating. Note that if you use the same variable name as an existing variable name it overwrites that column. Otherwise, it will add a column to your tibble.</p>
<p>To change the variable to a date - we are using a date parsing function from another package called <strong><code>lubridate</code></strong>. <code>mdy()</code> takes a character string or number in month-day-year format (as we have here) and returns a formal date object in YYYY-MM-DD format. There are similar functions if the input date is in year-month-day <code>ydm()</code> or day-month-year <code>dmy()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>measles_non_cumulative <span class="ot">&lt;-</span> measles_non_cumulative <span class="sc">%&gt;%</span> </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(<span class="at">PeriodStartDate =</span> <span class="fu">mdy</span>(PeriodStartDate),</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">PeriodEndDate =</span> <span class="fu">mdy</span>(PeriodEndDate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that you can mutate multiple columns at a time, separating each new column definition with a comma.</p>
<p>Now that R recognizes the date columns as Dates, we can do things like extract parts of the date, such as the year. Let’s create a separate Year column. Later we’ll be able to group our tibble by year for analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>measles_year <span class="ot">&lt;-</span> </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  measles_non_cumulative <span class="sc">%&gt;%</span> </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Year=</span><span class="fu">year</span>(PeriodStartDate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="grouping-and-summarizing" class="level2">
<h2 class="anchored" data-anchor-id="grouping-and-summarizing">Grouping and Summarizing</h2>
<p>Many data analysis tasks can be approached using the <em>split-apply-combine</em> paradigm: split the data into groups, apply some analysis to each group, and then combine the results. <strong><code>dplyr</code></strong> makes this very easy through the use of the <code>group_by()</code> function.</p>
<p><code>group_by()</code> is often used together with <code>summarize()</code>, which collapses each group into a single-row summary of that group. <code>group_by()</code> takes as arguments the column names that contain the <strong>categorical</strong> variables for which you want to calculate the summary statistics.</p>
<p>How can we calculate the total number of measles cases for each year?</p>
<p>First we need to group our data by year using our new <code>Year</code> column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>yearly_count <span class="ot">&lt;-</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  measles_year <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>yearly_count</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 332,138 × 6
# Groups:   Year [96]
   state   PeriodStartDate PeriodEndDate PartOfCumulativeCoun…¹ CountValue  Year
   &lt;chr&gt;   &lt;date&gt;          &lt;date&gt;                         &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt;
 1 WISCON… 1927-11-20      1927-11-26                         0         85  1927
 2 WISCON… 1927-11-27      1927-12-03                         0        120  1927
 3 WISCON… 1927-12-04      1927-12-10                         0         84  1927
 4 WISCON… 1927-12-18      1927-12-24                         0        106  1927
 5 WISCON… 1927-12-25      1927-12-31                         0         39  1927
 6 WISCON… 1928-01-01      1928-01-07                         0         45  1928
 7 WISCON… 1928-01-08      1928-01-14                         0         28  1928
 8 WISCON… 1928-01-15      1928-01-21                         0        140  1928
 9 WISCON… 1928-01-22      1928-01-28                         0         48  1928
10 WISCON… 1928-01-29      1928-02-04                         0         85  1928
# ℹ 332,128 more rows
# ℹ abbreviated name: ¹​PartOfCumulativeCountSeries</code></pre>
</div>
</div>
<p>When you inspect your new tibble, everything should look the same. Grouping prepares your data for summarize, but it does not do anything visually to the data.</p>
<p>Now let’s trying summarizing that data. <code>summarize()</code> condenses the value of the group values to a single value per group. Like <code>mutate()</code>, we provide the function with the name of the new column that will hold the summary information. In this case, we will use the <code>sum()</code> function on the <code>CountValue</code> column and put this in a new column called <code>TotalCount</code>. Summarize will drop the columns that aren’t being used.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>yearly_count <span class="ot">&lt;-</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  measles_year <span class="sc">%&gt;%</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">TotalCount =</span> <span class="fu">sum</span>(CountValue))</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>yearly_count</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 96 × 2
    Year TotalCount
   &lt;dbl&gt;      &lt;dbl&gt;
 1  1906       2345
 2  1907      40199
 3  1908      54471
 4  1909      49802
 5  1910      86984
 6  1911      59171
 7  1912      64773
 8  1913     111431
 9  1914      56440
10  1915      93579
# ℹ 86 more rows</code></pre>
</div>
</div>
<p>A more useful view might be to look for yearly totals of case counts by state. We can group by two variables, Year, and then State.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>yearly_count_state <span class="ot">&lt;-</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  measles_year <span class="sc">%&gt;%</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, state) <span class="sc">%&gt;%</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">TotalCount =</span> <span class="fu">sum</span>(CountValue))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Year'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>yearly_count_state</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,055 × 3
# Groups:   Year [96]
    Year state         TotalCount
   &lt;dbl&gt; &lt;chr&gt;              &lt;dbl&gt;
 1  1906 CALIFORNIA           224
 2  1906 CONNECTICUT           23
 3  1906 FLORIDA                4
 4  1906 ILLINOIS             187
 5  1906 INDIANA               20
 6  1906 KENTUCKY               2
 7  1906 MAINE                 26
 8  1906 MASSACHUSETTS        282
 9  1906 MICHIGAN             320
10  1906 MISSOURI             274
# ℹ 4,045 more rows</code></pre>
</div>
</div>
<p>Notice how the use of pipes really comes in handy here. It saved us from having to create and keep track of a number of intermediate objects.</p>
</section>
<section id="sorting-datasets-with-arrange" class="level2">
<h2 class="anchored" data-anchor-id="sorting-datasets-with-arrange">Sorting datasets with <code>arrange()</code></h2>
<p>Which state in which year had the highest case count? To easily find out, we can use the function <code>arrange()</code>. One of the arguments must be the column you want to sort on.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>yearly_count_state <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(TotalCount)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,055 × 3
# Groups:   Year [96]
    Year state       TotalCount
   &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;
 1  1925 NEVADA               0
 2  1937 MISSISSIPPI          0
 3  1938 MISSISSIPPI          0
 4  1939 MISSISSIPPI          0
 5  1940 MISSISSIPPI          0
 6  1940 NEVADA               0
 7  1941 MISSISSIPPI          0
 8  1944 MISSISSIPPI          0
 9  1945 MISSISSIPPI          0
10  1906 TEXAS                1
# ℹ 4,045 more rows</code></pre>
</div>
</div>
<p>By default, arrange sorts in ascending order. To sort by descending order we use together with the <code>desc()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>yearly_count_state <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(TotalCount))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,055 × 3
# Groups:   Year [96]
    Year state        TotalCount
   &lt;dbl&gt; &lt;chr&gt;             &lt;dbl&gt;
 1  1938 PENNSYLVANIA     146467
 2  1941 PENNSYLVANIA     137180
 3  1938 ILLINOIS         127935
 4  1942 CALIFORNIA       116180
 5  1941 OHIO             114788
 6  1935 MICHIGAN         111413
 7  1941 NEW YORK         109663
 8  1938 MICHIGAN         109041
 9  1934 PENNSYLVANIA     107031
10  1938 WISCONSIN        104450
# ℹ 4,045 more rows</code></pre>
</div>
</div>
</section>
<section id="joining-datasets" class="level2">
<h2 class="anchored" data-anchor-id="joining-datasets">Joining Datasets</h2>
<p>Of course, looking at total counts in each state is not the most helpful metric without taking population into account. To rectify this, let’s try joining some historical population data with our measles data.</p>
<p>First we need to import the population data<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>hist_pop <span class="ot">&lt;-</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_csv</span>(<span class="st">"data/Historical_Population_by_State.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 107 Columns: 52
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (52): DATE, ALASKA, ALABAMA, ARKANSAS, ARIZONA, CALIFORNIA, COLORADO, CO...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</section>
<section id="long-vs-wide-formats" class="level2">
<h2 class="anchored" data-anchor-id="long-vs-wide-formats">Long vs Wide formats</h2>
<p>Remember that for data to be considered “tidy”, it should be in what is called “long” format. Each column is a variable, each row is an observation, and each cell is a value. Our state population data is in “wide” format, because State Name is being treated as a variable, when it is really a value. Wide data is often preferable for human-readability, but is less ideal for machine-readability. To be able to join this data to our measles dataset, it needs to have 3 columns - Year, State Name, and Population.</p>
<p>We will use the package <strong><code>tidyr</code></strong> and the function <code>pivot_longer</code> to convert our population data to a long format, thus making it easier to join with our measles data.</p>
<p>Each column in our population dataset represents a state. To make it tidy we are going to reduce those to one column called State with the state names as the values of the column. We will then need to create a new column for population containing the current cell values. To remember that the population data is provided in 1000s of persons, we will call this new column pop1000.</p>
<p><code>pivot_longer()</code> takes four principal arguments:</p>
<ol type="1">
<li>the data</li>
<li><em>cols</em> are the names of the columns we use to fill the new values variable (or to drop).</li>
<li>the <em>names_to</em> column variable we wish to create from the <em>cols</em> provided.</li>
<li>the <em>values_to</em> column variable we wish to create and fill with values associated with the <em>cols</em> provided.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>hist_pop_long <span class="ot">&lt;-</span> hist_pop <span class="sc">%&gt;%</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(ALASKA<span class="sc">:</span>WYOMING,</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"state"</span>,</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"pop1000"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(hist_pop_long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now our two datasets have similar structures, a column of state names, a column of years, and a column of values. Let’s join these two datasets by the state and year columns. Note that if both sets have the same column names, you do not need to specify anything in the by argument. We use a left join here which preserves all the rows in our measles dataset and adds the matching rows from the population dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>measles_joined<span class="ot">&lt;-</span> yearly_count_state <span class="sc">%&gt;%</span> </span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(hist_pop_long, <span class="at">by=</span><span class="fu">join_by</span>(state, Year <span class="sc">==</span> DATE))</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>measles_joined</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,055 × 4
# Groups:   Year [96]
    Year state         TotalCount pop1000
   &lt;dbl&gt; &lt;chr&gt;              &lt;dbl&gt;   &lt;dbl&gt;
 1  1906 CALIFORNIA           224    1976
 2  1906 CONNECTICUT           23    1033
 3  1906 FLORIDA                4     628
 4  1906 ILLINOIS             187    5309
 5  1906 INDIANA               20    2663
 6  1906 KENTUCKY               2    2234
 7  1906 MAINE                 26     729
 8  1906 MASSACHUSETTS        282    3107
 9  1906 MICHIGAN             320    2626
10  1906 MISSOURI             274    3223
# ℹ 4,045 more rows</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="CHALLENGE">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
CHALLENGE
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Use <code>mutate()</code> to calculate the rate of measles per 100,000 persons (remember population is given in 1000s).</p></li>
<li><p>Try joining <code>measles_yearly_rates</code> to <code>states</code>. What variable do you need to join by?</p></li>
</ol>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. </span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>measles_yearly_rates <span class="ot">&lt;-</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  measles_joined <span class="sc">%&gt;%</span> </span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">epi_rate =</span> (TotalCount <span class="sc">/</span> pop1000)<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. </span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>yearly_rates_joined <span class="ot">&lt;-</span> measles_yearly_rates <span class="sc">%&gt;%</span> </span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(states, <span class="at">by =</span> <span class="fu">join_by</span>(state <span class="sc">==</span> name))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>Now our data is ready to be visualized!</p>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>https://www.tidyverse.org/<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>read more about tidy data https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>image from R for Data Science https://r4ds.had.co.nz/tidy-data.html#fig:tidy-structure<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>population data retrieved from the FRED, the Federal Reserve Bank of St.&nbsp;Louis Economic Data, https://fred.stlouisfed.org/release/tables?rid=118&amp;eid=259194<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/hshsl-training\.github\.io\/intro-to-r\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://hshsl-training.github.io/intro-to-r/edit/main/02-DataWrangling.qmd" class="toc-action"><i class="bi bi-git"></i>Edit this page</a></li><li><a href="https://hshsl-training.github.io/intro-to-r/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p><a href="https://creativecommons.org/licenses/by-sa/4.0/"><img src="https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by.svg" class="img-fluid" alt="CC BY" width="125"></a></p>
</div>
  </div>
</footer>




</body></html>